from bdbag.bdbag_config import *
from bdbag import get_typed_exception as get_typed_exception, stob as stob
from typing import Any

def find_cookie_jars(cookie_jar_config: Any | None = ...): ...
def load_and_merge_cookie_jars(cookie_jar_paths): ...
def get_request_cookies(config): ...
