from bdbag import DEFAULT_CONFIG_PATH as DEFAULT_CONFIG_PATH
from bdbag.bdbagit import force_unicode as force_unicode
from typing import Any

logger: Any
DEFAULT_KEYCHAIN_FILE: Any
DEFAULT_KEYCHAIN: Any
KEYCHAIN_EXAMPLE: Any

def write_keychain(keychain=..., keychain_file=...) -> None: ...
def read_keychain(keychain_file=..., create_default: bool = ...): ...
def update_keychain(
    keychain_entries, keychain_file: Any | None = ..., delete: bool = ...
): ...
def has_auth_attr(auth, attr, quiet: bool = ...): ...
def get_auth_entries(url, auth): ...
