from rdflib.parser import PythonInputSource as PythonInputSource, StringInputSource as StringInputSource, create_input_source as create_input_source
from typing import Any

def source_to_json(source): ...

VOCAB_DELIMS: Any

def split_iri(iri): ...
def norm_url(base, url): ...
def context_from_urlinputsource(source): ...
