from rdflib.graph import Graph
from rdflib.plugins.serializers.turtle import TurtleSerializer
from typing import Any

class N3Serializer(TurtleSerializer):
    short_name: str
    parent: Any
    def __init__(self, store: Graph, parent: Any | None = ...) -> None: ...
    def reset(self) -> None: ...
    def subjectDone(self, subject) -> None: ...
    def isDone(self, subject): ...
    def startDocument(self) -> None: ...
    def endDocument(self) -> None: ...
    def indent(self, modifier: int = ...): ...
    def preprocessTriple(self, triple) -> None: ...
    def getQName(self, uri, gen_prefix: bool = ...): ...
    def statement(self, subject): ...
    def path(self, node, position, newline: bool = ...) -> None: ...
    def s_clause(self, subject): ...
    def p_clause(self, node, position): ...
