from rdflib.namespace import DefinedNamespace as DefinedNamespace, Namespace as Namespace
from rdflib.term import URIRef as URIRef

class BRICK(DefinedNamespace):
    AED: URIRef
    AHU: URIRef
    Ablutions_Room: URIRef
    Absorption_Chiller: URIRef
    Acceleration_Time_Setpoint: URIRef
    Access_Control_Equipment: URIRef
    Access_Reader: URIRef
    Active_Chilled_Beam: URIRef
    Active_Power_Sensor: URIRef
    Adjust_Sensor: URIRef
    Air: URIRef
    Air_Alarm: URIRef
    Air_Differential_Pressure_Sensor: URIRef
    Air_Differential_Pressure_Setpoint: URIRef
    Air_Diffuser: URIRef
    Air_Enthalpy_Sensor: URIRef
    Air_Flow_Deadband_Setpoint: URIRef
    Air_Flow_Demand_Setpoint: URIRef
    Air_Flow_Loss_Alarm: URIRef
    Air_Flow_Sensor: URIRef
    Air_Flow_Setpoint: URIRef
    Air_Flow_Setpoint_Limit: URIRef
    Air_Grains_Sensor: URIRef
    Air_Handler_Unit: URIRef
    Air_Handling_Unit: URIRef
    Air_Humidity_Setpoint: URIRef
    Air_Loop: URIRef
    Air_Plenum: URIRef
    Air_Quality_Sensor: URIRef
    Air_Static_Pressure_Step_Parameter: URIRef
    Air_System: URIRef
    Air_Temperature_Alarm: URIRef
    Air_Temperature_Integral_Time_Parameter: URIRef
    Air_Temperature_Sensor: URIRef
    Air_Temperature_Setpoint: URIRef
    Air_Temperature_Setpoint_Limit: URIRef
    Air_Temperature_Step_Parameter: URIRef
    Air_Wet_Bulb_Temperature_Sensor: URIRef
    Alarm: URIRef
    Alarm_Delay_Parameter: URIRef
    Angle_Sensor: URIRef
    Auditorium: URIRef
    Automated_External_Defibrillator: URIRef
    Automatic_Mode_Command: URIRef
    Availability_Status: URIRef
    Average_Cooling_Demand_Sensor: URIRef
    Average_Discharge_Air_Flow_Sensor: URIRef
    Average_Exhaust_Air_Static_Pressure_Sensor: URIRef
    Average_Heating_Demand_Sensor: URIRef
    Average_Supply_Air_Flow_Sensor: URIRef
    Average_Zone_Air_Temperature_Sensor: URIRef
    Baseboard_Radiator: URIRef
    Basement: URIRef
    Battery: URIRef
    Battery_Energy_Storage_System: URIRef
    Battery_Room: URIRef
    Battery_Voltage_Sensor: URIRef
    Bench_Space: URIRef
    Blowdown_Water: URIRef
    Boiler: URIRef
    Booster_Fan: URIRef
    Box_Mode_Command: URIRef
    Break_Room: URIRef
    Breaker_Panel: URIRef
    Breakroom: URIRef
    Broadcast_Room: URIRef
    Building: URIRef
    Building_Air: URIRef
    Building_Air_Humidity_Setpoint: URIRef
    Building_Air_Static_Pressure_Sensor: URIRef
    Building_Air_Static_Pressure_Setpoint: URIRef
    Building_Chilled_Water_Meter: URIRef
    Building_Electrical_Meter: URIRef
    Building_Gas_Meter: URIRef
    Building_Hot_Water_Meter: URIRef
    Building_Meter: URIRef
    Building_Water_Meter: URIRef
    Bus_Riser: URIRef
    Bypass_Air: URIRef
    Bypass_Air_Flow_Sensor: URIRef
    Bypass_Air_Humidity_Setpoint: URIRef
    Bypass_Command: URIRef
    Bypass_Valve: URIRef
    Bypass_Water: URIRef
    Bypass_Water_Flow_Sensor: URIRef
    Bypass_Water_Flow_Setpoint: URIRef
    CAV: URIRef
    CO: URIRef
    CO2: URIRef
    CO2_Alarm: URIRef
    CO2_Differential_Sensor: URIRef
    CO2_Level_Sensor: URIRef
    CO2_Sensor: URIRef
    CO2_Setpoint: URIRef
    CO_Differential_Sensor: URIRef
    CO_Level_Sensor: URIRef
    CO_Sensor: URIRef
    CRAC: URIRef
    Cafeteria: URIRef
    Camera: URIRef
    Capacity_Sensor: URIRef
    Ceiling_Fan: URIRef
    Centrifugal_Chiller: URIRef
    Change_Filter_Alarm: URIRef
    Chilled_Beam: URIRef
    Chilled_Water: URIRef
    Chilled_Water_Coil: URIRef
    Chilled_Water_Differential_Pressure_Deadband_Setpoint: URIRef
    Chilled_Water_Differential_Pressure_Integral_Time_Parameter: URIRef
    Chilled_Water_Differential_Pressure_Load_Shed_Reset_Status: URIRef
    Chilled_Water_Differential_Pressure_Load_Shed_Setpoint: URIRef
    Chilled_Water_Differential_Pressure_Load_Shed_Status: URIRef
    Chilled_Water_Differential_Pressure_Proportional_Band_Parameter: URIRef
    Chilled_Water_Differential_Pressure_Sensor: URIRef
    Chilled_Water_Differential_Pressure_Setpoint: URIRef
    Chilled_Water_Differential_Pressure_Step_Parameter: URIRef
    Chilled_Water_Differential_Temperature_Sensor: URIRef
    Chilled_Water_Discharge_Flow_Sensor: URIRef
    Chilled_Water_Discharge_Flow_Setpoint: URIRef
    Chilled_Water_Flow_Sensor: URIRef
    Chilled_Water_Flow_Setpoint: URIRef
    Chilled_Water_Loop: URIRef
    Chilled_Water_Meter: URIRef
    Chilled_Water_Pump: URIRef
    Chilled_Water_Pump_Differential_Pressure_Deadband_Setpoint: URIRef
    Chilled_Water_Return_Flow_Sensor: URIRef
    Chilled_Water_Return_Temperature_Sensor: URIRef
    Chilled_Water_Static_Pressure_Setpoint: URIRef
    Chilled_Water_Supply_Flow_Sensor: URIRef
    Chilled_Water_Supply_Flow_Setpoint: URIRef
    Chilled_Water_Supply_Temperature_Sensor: URIRef
    Chilled_Water_System: URIRef
    Chilled_Water_System_Enable_Command: URIRef
    Chilled_Water_Temperature_Sensor: URIRef
    Chilled_Water_Temperature_Setpoint: URIRef
    Chilled_Water_Valve: URIRef
    Chiller: URIRef
    Class: URIRef
    Close_Limit: URIRef
    Coil: URIRef
    Cold_Box: URIRef
    Coldest_Zone_Air_Temperature_Sensor: URIRef
    Collection: URIRef
    Collection_Basin_Water: URIRef
    Collection_Basin_Water_Heater: URIRef
    Collection_Basin_Water_Level_Alarm: URIRef
    Collection_Basin_Water_Level_Sensor: URIRef
    Collection_Basin_Water_Temperature_Sensor: URIRef
    Command: URIRef
    Common_Space: URIRef
    Communication_Loss_Alarm: URIRef
    Compressor: URIRef
    Computer_Room_Air_Conditioning: URIRef
    Concession: URIRef
    Condensate_Leak_Alarm: URIRef
    Condenser: URIRef
    Condenser_Heat_Exchanger: URIRef
    Condenser_Water: URIRef
    Condenser_Water_Bypass_Valve: URIRef
    Condenser_Water_Isolation_Valve: URIRef
    Condenser_Water_Pump: URIRef
    Condenser_Water_System: URIRef
    Condenser_Water_Temperature_Sensor: URIRef
    Condenser_Water_Valve: URIRef
    Condensing_Natural_Gas_Boiler: URIRef
    Conductivity_Sensor: URIRef
    Conference_Room: URIRef
    Constant_Air_Volume_Box: URIRef
    Contact_Sensor: URIRef
    Control_Room: URIRef
    Cooling_Coil: URIRef
    Cooling_Command: URIRef
    Cooling_Demand_Sensor: URIRef
    Cooling_Demand_Setpoint: URIRef
    Cooling_Discharge_Air_Flow_Setpoint: URIRef
    Cooling_Discharge_Air_Temperature_Deadband_Setpoint: URIRef
    Cooling_Discharge_Air_Temperature_Integral_Time_Parameter: URIRef
    Cooling_Discharge_Air_Temperature_Proportional_Band_Parameter: URIRef
    Cooling_Start_Stop_Status: URIRef
    Cooling_Supply_Air_Flow_Setpoint: URIRef
    Cooling_Supply_Air_Temperature_Deadband_Setpoint: URIRef
    Cooling_Supply_Air_Temperature_Integral_Time_Parameter: URIRef
    Cooling_Supply_Air_Temperature_Proportional_Band_Parameter: URIRef
    Cooling_Temperature_Setpoint: URIRef
    Cooling_Tower: URIRef
    Cooling_Tower_Fan: URIRef
    Cooling_Valve: URIRef
    Copy_Room: URIRef
    Core_Temperature_Sensor: URIRef
    Core_Temperature_Setpoint: URIRef
    Cubicle: URIRef
    Current_Imbalance_Sensor: URIRef
    Current_Limit: URIRef
    Current_Output_Sensor: URIRef
    Current_Sensor: URIRef
    Curtailment_Override_Command: URIRef
    Cycle_Alarm: URIRef
    DC_Bus_Voltage_Sensor: URIRef
    DOAS: URIRef
    Damper: URIRef
    Damper_Command: URIRef
    Damper_Position_Command: URIRef
    Damper_Position_Sensor: URIRef
    Damper_Position_Setpoint: URIRef
    Deadband_Setpoint: URIRef
    Deceleration_Time_Setpoint: URIRef
    Dedicated_Outdoor_Air_System_Unit: URIRef
    Dehumidification_Start_Stop_Status: URIRef
    Deionised_Water_Conductivity_Sensor: URIRef
    Deionised_Water_Level_Sensor: URIRef
    Deionized_Water: URIRef
    Deionized_Water_Alarm: URIRef
    Delay_Parameter: URIRef
    Demand_Sensor: URIRef
    Demand_Setpoint: URIRef
    Derivative_Gain_Parameter: URIRef
    Derivative_Time_Parameter: URIRef
    Detention_Room: URIRef
    Dew_Point_Setpoint: URIRef
    Dewpoint_Sensor: URIRef
    Differential_Air_Temperature_Setpoint: URIRef
    Differential_Pressure_Bypass_Valve: URIRef
    Differential_Pressure_Deadband_Setpoint: URIRef
    Differential_Pressure_Integral_Time_Parameter: URIRef
    Differential_Pressure_Load_Shed_Status: URIRef
    Differential_Pressure_Proportional_Band: URIRef
    Differential_Pressure_Sensor: URIRef
    Differential_Pressure_Setpoint: URIRef
    Differential_Pressure_Setpoint_Limit: URIRef
    Differential_Pressure_Step_Parameter: URIRef
    Differential_Speed_Sensor: URIRef
    Differential_Speed_Setpoint: URIRef
    Differential_Supply_Return_Water_Temperature_Sensor: URIRef
    Dimmer: URIRef
    Direct_Expansion_Cooling_Coil: URIRef
    Direct_Expansion_Heating_Coil: URIRef
    Direction_Command: URIRef
    Direction_Sensor: URIRef
    Direction_Status: URIRef
    Disable_Command: URIRef
    Disable_Differential_Enthalpy_Command: URIRef
    Disable_Differential_Temperature_Command: URIRef
    Disable_Fixed_Enthalpy_Command: URIRef
    Disable_Fixed_Temperature_Command: URIRef
    Disable_Hot_Water_System_Outside_Air_Temperature_Setpoint: URIRef
    Disable_Status: URIRef
    Discharge_Air: URIRef
    Discharge_Air_Dewpoint_Sensor: URIRef
    Discharge_Air_Duct_Pressure_Status: URIRef
    Discharge_Air_Flow_Demand_Setpoint: URIRef
    Discharge_Air_Flow_High_Reset_Setpoint: URIRef
    Discharge_Air_Flow_Low_Reset_Setpoint: URIRef
    Discharge_Air_Flow_Reset_Setpoint: URIRef
    Discharge_Air_Flow_Sensor: URIRef
    Discharge_Air_Flow_Setpoint: URIRef
    Discharge_Air_Humidity_Sensor: URIRef
    Discharge_Air_Humidity_Setpoint: URIRef
    Discharge_Air_Smoke_Detection_Alarm: URIRef
    Discharge_Air_Static_Pressure_Deadband_Setpoint: URIRef
    Discharge_Air_Static_Pressure_Integral_Time_Parameter: URIRef
    Discharge_Air_Static_Pressure_Proportional_Band_Parameter: URIRef
    Discharge_Air_Static_Pressure_Sensor: URIRef
    Discharge_Air_Static_Pressure_Setpoint: URIRef
    Discharge_Air_Static_Pressure_Step_Parameter: URIRef
    Discharge_Air_Temperature_Alarm: URIRef
    Discharge_Air_Temperature_Cooling_Setpoint: URIRef
    Discharge_Air_Temperature_Deadband_Setpoint: URIRef
    Discharge_Air_Temperature_Heating_Setpoint: URIRef
    Discharge_Air_Temperature_High_Reset_Setpoint: URIRef
    Discharge_Air_Temperature_Low_Reset_Setpoint: URIRef
    Discharge_Air_Temperature_Proportional_Band_Parameter: URIRef
    Discharge_Air_Temperature_Reset_Differential_Setpoint: URIRef
    Discharge_Air_Temperature_Sensor: URIRef
    Discharge_Air_Temperature_Setpoint: URIRef
    Discharge_Air_Temperature_Setpoint_Limit: URIRef
    Discharge_Air_Temperature_Step_Parameter: URIRef
    Discharge_Air_Velocity_Pressure_Sensor: URIRef
    Discharge_Chilled_Water: URIRef
    Discharge_Fan: URIRef
    Discharge_Hot_Water: URIRef
    Discharge_Water: URIRef
    Discharge_Water_Differential_Pressure_Deadband_Setpoint: URIRef
    Discharge_Water_Differential_Pressure_Integral_Time_Parameter: URIRef
    Discharge_Water_Differential_Pressure_Proportional_Band_Parameter: URIRef
    Discharge_Water_Flow_Sensor: URIRef
    Discharge_Water_Flow_Setpoint: URIRef
    Discharge_Water_Temperature_Alarm: URIRef
    Discharge_Water_Temperature_Proportional_Band_Parameter: URIRef
    Discharge_Water_Temperature_Sensor: URIRef
    Discharge_Water_Temperature_Setpoint: URIRef
    Disconnect_Switch: URIRef
    Displacement_Flow_Air_Diffuser: URIRef
    Distribution_Frame: URIRef
    Domestic_Hot_Water_Supply_Temperature_Sensor: URIRef
    Domestic_Hot_Water_Supply_Temperature_Setpoint: URIRef
    Domestic_Hot_Water_System: URIRef
    Domestic_Hot_Water_System_Enable_Command: URIRef
    Domestic_Hot_Water_Temperature_Setpoint: URIRef
    Domestic_Hot_Water_Valve: URIRef
    Domestic_Water: URIRef
    Domestic_Water_Loop: URIRef
    Drench_Hose: URIRef
    Drive_Ready_Status: URIRef
    Duration_Sensor: URIRef
    ESS_Panel: URIRef
    EconCycle_Start_Stop_Status: URIRef
    Economizer: URIRef
    Economizer_Damper: URIRef
    Effective_Air_Temperature_Cooling_Setpoint: URIRef
    Effective_Air_Temperature_Heating_Setpoint: URIRef
    Effective_Air_Temperature_Setpoint: URIRef
    Effective_Discharge_Air_Temperature_Setpoint: URIRef
    Effective_Return_Air_Temperature_Setpoint: URIRef
    Effective_Room_Air_Temperature_Setpoint: URIRef
    Effective_Supply_Air_Temperature_Setpoint: URIRef
    Effective_Zone_Air_Temperature_Setpoint: URIRef
    Electric_Baseboard_Radiator: URIRef
    Electric_Boiler: URIRef
    Electric_Radiator: URIRef
    Electrical_Equipment: URIRef
    Electrical_Meter: URIRef
    Electrical_Power_Sensor: URIRef
    Electrical_Room: URIRef
    Electrical_System: URIRef
    Elevator: URIRef
    Elevator_Shaft: URIRef
    Elevator_Space: URIRef
    Embedded_Surface_System_Panel: URIRef
    Embedded_Temperature_Sensor: URIRef
    Embedded_Temperature_Setpoint: URIRef
    Emergency_Air_Flow_System: URIRef
    Emergency_Air_Flow_System_Status: URIRef
    Emergency_Alarm: URIRef
    Emergency_Generator_Alarm: URIRef
    Emergency_Generator_Status: URIRef
    Emergency_Phone: URIRef
    Emergency_Power_Off_System: URIRef
    Emergency_Power_Off_System_Activated_By_High_Temperature_Status: URIRef
    Emergency_Power_Off_System_Activated_By_Leak_Detection_System_Status: URIRef
    Emergency_Power_Off_System_Status: URIRef
    Emergency_Push_Button_Status: URIRef
    Emergency_Wash_Station: URIRef
    Employee_Entrance_Lobby: URIRef
    Enable_Command: URIRef
    Enable_Differential_Enthalpy_Command: URIRef
    Enable_Differential_Temperature_Command: URIRef
    Enable_Fixed_Enthalpy_Command: URIRef
    Enable_Fixed_Temperature_Command: URIRef
    Enable_Hot_Water_System_Outside_Air_Temperature_Setpoint: URIRef
    Enable_Status: URIRef
    Enclosed_Office: URIRef
    Energy_Generation_System: URIRef
    Energy_Sensor: URIRef
    Energy_Storage: URIRef
    Energy_Storage_System: URIRef
    Energy_System: URIRef
    Energy_Usage_Sensor: URIRef
    Energy_Zone: URIRef
    Entering_Water: URIRef
    Entering_Water_Flow_Sensor: URIRef
    Entering_Water_Flow_Setpoint: URIRef
    Entering_Water_Temperature_Sensor: URIRef
    Entering_Water_Temperature_Setpoint: URIRef
    Enthalpy_Sensor: URIRef
    Enthalpy_Setpoint: URIRef
    Entrance: URIRef
    Environment_Box: URIRef
    Equipment: URIRef
    Equipment_Room: URIRef
    Evaporative_Heat_Exchanger: URIRef
    Even_Month_Status: URIRef
    Exercise_Room: URIRef
    Exhaust_Air: URIRef
    Exhaust_Air_Dewpoint_Sensor: URIRef
    Exhaust_Air_Differential_Pressure_Sensor: URIRef
    Exhaust_Air_Differential_Pressure_Setpoint: URIRef
    Exhaust_Air_Flow_Integral_Time_Parameter: URIRef
    Exhaust_Air_Flow_Proportional_Band_Parameter: URIRef
    Exhaust_Air_Flow_Sensor: URIRef
    Exhaust_Air_Flow_Setpoint: URIRef
    Exhaust_Air_Humidity_Sensor: URIRef
    Exhaust_Air_Humidity_Setpoint: URIRef
    Exhaust_Air_Stack_Flow_Deadband_Setpoint: URIRef
    Exhaust_Air_Stack_Flow_Integral_Time_Parameter: URIRef
    Exhaust_Air_Stack_Flow_Proportional_Band_Parameter: URIRef
    Exhaust_Air_Stack_Flow_Sensor: URIRef
    Exhaust_Air_Stack_Flow_Setpoint: URIRef
    Exhaust_Air_Static_Pressure_Proportional_Band_Parameter: URIRef
    Exhaust_Air_Static_Pressure_Sensor: URIRef
    Exhaust_Air_Static_Pressure_Setpoint: URIRef
    Exhaust_Air_Temperature_Sensor: URIRef
    Exhaust_Air_Velocity_Pressure_Sensor: URIRef
    Exhaust_Damper: URIRef
    Exhaust_Fan: URIRef
    Exhaust_Fan_Disable_Command: URIRef
    Exhaust_Fan_Enable_Command: URIRef
    Eye_Wash_Station: URIRef
    FCU: URIRef
    Failure_Alarm: URIRef
    Fan: URIRef
    Fan_Coil_Unit: URIRef
    Fan_On_Off_Status: URIRef
    Fan_Status: URIRef
    Fan_VFD: URIRef
    Fault_Reset_Command: URIRef
    Fault_Status: URIRef
    Field_Of_Play: URIRef
    Filter: URIRef
    Filter_Differential_Pressure_Sensor: URIRef
    Filter_Reset_Command: URIRef
    Filter_Status: URIRef
    Final_Filter: URIRef
    Fire_Control_Panel: URIRef
    Fire_Safety_Equipment: URIRef
    Fire_Safety_System: URIRef
    Fire_Sensor: URIRef
    Fire_Zone: URIRef
    First_Aid_Kit: URIRef
    First_Aid_Room: URIRef
    Floor: URIRef
    Flow_Sensor: URIRef
    Flow_Setpoint: URIRef
    Fluid: URIRef
    Food_Service_Room: URIRef
    Formaldehyde_Level_Sensor: URIRef
    Freeze_Status: URIRef
    Freezer: URIRef
    Frequency_Command: URIRef
    Frequency_Sensor: URIRef
    Fresh_Air_Fan: URIRef
    Fresh_Air_Setpoint_Limit: URIRef
    Frost: URIRef
    Frost_Sensor: URIRef
    Fuel_Oil: URIRef
    Fume_Hood: URIRef
    Fume_Hood_Air_Flow_Sensor: URIRef
    Furniture: URIRef
    Gain_Parameter: URIRef
    Gas: URIRef
    Gas_Distribution: URIRef
    Gas_Meter: URIRef
    Gas_Sensor: URIRef
    Gas_System: URIRef
    Gas_Valve: URIRef
    Gasoline: URIRef
    Gatehouse: URIRef
    Generator_Room: URIRef
    Glycol: URIRef
    HVAC_Equipment: URIRef
    HVAC_System: URIRef
    HVAC_Zone: URIRef
    HX: URIRef
    Hail: URIRef
    Hail_Sensor: URIRef
    Hallway: URIRef
    Hazardous_Materials_Storage: URIRef
    Heat_Exchanger: URIRef
    Heat_Exchanger_Supply_Water_Temperature_Sensor: URIRef
    Heat_Exchanger_System_Enable_Status: URIRef
    Heat_Recovery_Hot_Water_System: URIRef
    Heat_Sensor: URIRef
    Heat_Wheel: URIRef
    Heat_Wheel_VFD: URIRef
    Heating_Coil: URIRef
    Heating_Command: URIRef
    Heating_Demand_Sensor: URIRef
    Heating_Demand_Setpoint: URIRef
    Heating_Discharge_Air_Flow_Setpoint: URIRef
    Heating_Discharge_Air_Temperature_Deadband_Setpoint: URIRef
    Heating_Discharge_Air_Temperature_Integral_Time_Parameter: URIRef
    Heating_Discharge_Air_Temperature_Proportional_Band_Parameter: URIRef
    Heating_Start_Stop_Status: URIRef
    Heating_Supply_Air_Flow_Setpoint: URIRef
    Heating_Supply_Air_Temperature_Deadband_Setpoint: URIRef
    Heating_Supply_Air_Temperature_Integral_Time_Parameter: URIRef
    Heating_Supply_Air_Temperature_Proportional_Band_Parameter: URIRef
    Heating_Temperature_Setpoint: URIRef
    Heating_Thermal_Power_Sensor: URIRef
    Heating_Valve: URIRef
    Heating_Ventilation_Air_Conditioning_System: URIRef
    High_CO2_Alarm: URIRef
    High_Discharge_Air_Temperature_Alarm: URIRef
    High_Head_Pressure_Alarm: URIRef
    High_Humidity_Alarm: URIRef
    High_Humidity_Alarm_Parameter: URIRef
    High_Outside_Air_Lockout_Temperature_Differential_Parameter: URIRef
    High_Return_Air_Temperature_Alarm: URIRef
    High_Static_Pressure_Cutout_Setpoint_Limit: URIRef
    High_Temperature_Alarm: URIRef
    High_Temperature_Alarm_Parameter: URIRef
    High_Temperature_Hot_Water_Return_Temperature_Sensor: URIRef
    High_Temperature_Hot_Water_Supply_Temperature_Sensor: URIRef
    Hold_Status: URIRef
    Hospitality_Box: URIRef
    Hot_Box: URIRef
    Hot_Water: URIRef
    Hot_Water_Baseboard_Radiator: URIRef
    Hot_Water_Coil: URIRef
    Hot_Water_Differential_Pressure_Deadband_Setpoint: URIRef
    Hot_Water_Differential_Pressure_Integral_Time_Parameter: URIRef
    Hot_Water_Differential_Pressure_Load_Shed_Reset_Status: URIRef
    Hot_Water_Differential_Pressure_Load_Shed_Status: URIRef
    Hot_Water_Differential_Pressure_Proportional_Band_Parameter: URIRef
    Hot_Water_Differential_Pressure_Sensor: URIRef
    Hot_Water_Differential_Pressure_Setpoint: URIRef
    Hot_Water_Differential_Temperature_Sensor: URIRef
    Hot_Water_Discharge_Flow_Sensor: URIRef
    Hot_Water_Discharge_Flow_Setpoint: URIRef
    Hot_Water_Discharge_Temperature_Load_Shed_Status: URIRef
    Hot_Water_Flow_Sensor: URIRef
    Hot_Water_Flow_Setpoint: URIRef
    Hot_Water_Loop: URIRef
    Hot_Water_Meter: URIRef
    Hot_Water_Pump: URIRef
    Hot_Water_Radiator: URIRef
    Hot_Water_Return_Flow_Sensor: URIRef
    Hot_Water_Return_Temperature_Sensor: URIRef
    Hot_Water_Static_Pressure_Setpoint: URIRef
    Hot_Water_Supply_Flow_Sensor: URIRef
    Hot_Water_Supply_Flow_Setpoint: URIRef
    Hot_Water_Supply_Temperature_High_Reset_Setpoint: URIRef
    Hot_Water_Supply_Temperature_Load_Shed_Status: URIRef
    Hot_Water_Supply_Temperature_Low_Reset_Setpoint: URIRef
    Hot_Water_Supply_Temperature_Sensor: URIRef
    Hot_Water_System: URIRef
    Hot_Water_System_Enable_Command: URIRef
    Hot_Water_Temperature_Setpoint: URIRef
    Hot_Water_Usage_Sensor: URIRef
    Hot_Water_Valve: URIRef
    Humidification_Start_Stop_Status: URIRef
    Humidifier: URIRef
    Humidifier_Fault_Status: URIRef
    Humidify_Command: URIRef
    Humidity_Alarm: URIRef
    Humidity_Parameter: URIRef
    Humidity_Sensor: URIRef
    Humidity_Setpoint: URIRef
    Humidity_Tolerance_Parameter: URIRef
    IDF: URIRef
    Ice: URIRef
    Ice_Tank_Leaving_Water_Temperature_Sensor: URIRef
    Illuminance_Sensor: URIRef
    Imbalance_Sensor: URIRef
    Induction_Unit: URIRef
    Information_Area: URIRef
    Inside_Face_Surface_Temperature_Sensor: URIRef
    Inside_Face_Surface_Temperature_Setpoint: URIRef
    Intake_Air_Filter: URIRef
    Intake_Air_Temperature_Sensor: URIRef
    Integral_Gain_Parameter: URIRef
    Integral_Time_Parameter: URIRef
    Intercom_Equipment: URIRef
    Interface: URIRef
    Intrusion_Detection_Equipment: URIRef
    Inverter: URIRef
    Isolation_Valve: URIRef
    Janitor_Room: URIRef
    Jet_Nozzle_Air_Diffuser: URIRef
    Laboratory: URIRef
    Laminar_Flow_Air_Diffuser: URIRef
    Last_Fault_Code_Status: URIRef
    Lead_Lag_Command: URIRef
    Lead_Lag_Status: URIRef
    Lead_On_Off_Command: URIRef
    Leak_Alarm: URIRef
    Leaving_Water: URIRef
    Leaving_Water_Flow_Sensor: URIRef
    Leaving_Water_Flow_Setpoint: URIRef
    Leaving_Water_Temperature_Sensor: URIRef
    Leaving_Water_Temperature_Setpoint: URIRef
    Library: URIRef
    Lighting: URIRef
    Lighting_Equipment: URIRef
    Lighting_System: URIRef
    Lighting_Zone: URIRef
    Limit: URIRef
    Liquid: URIRef
    Liquid_CO2: URIRef
    Liquid_Detection_Alarm: URIRef
    Load_Current_Sensor: URIRef
    Load_Parameter: URIRef
    Load_Setpoint: URIRef
    Load_Shed_Command: URIRef
    Load_Shed_Differential_Pressure_Setpoint: URIRef
    Load_Shed_Setpoint: URIRef
    Load_Shed_Status: URIRef
    Loading_Dock: URIRef
    Lobby: URIRef
    Locally_On_Off_Status: URIRef
    Location: URIRef
    Lockout_Status: URIRef
    Lockout_Temperature_Differential_Parameter: URIRef
    Loop: URIRef
    Lounge: URIRef
    Louver: URIRef
    Low_Freeze_Protect_Temperature_Parameter: URIRef
    Low_Humidity_Alarm: URIRef
    Low_Humidity_Alarm_Parameter: URIRef
    Low_Outside_Air_Lockout_Temperature_Differential_Parameter: URIRef
    Low_Outside_Air_Temperature_Enable_Differential_Sensor: URIRef
    Low_Outside_Air_Temperature_Enable_Setpoint: URIRef
    Low_Return_Air_Temperature_Alarm: URIRef
    Low_Suction_Pressure_Alarm: URIRef
    Low_Temperature_Alarm: URIRef
    Low_Temperature_Alarm_Parameter: URIRef
    Lowest_Exhaust_Air_Static_Pressure_Sensor: URIRef
    Luminaire: URIRef
    Luminaire_Driver: URIRef
    Luminance_Alarm: URIRef
    Luminance_Command: URIRef
    Luminance_Sensor: URIRef
    Luminance_Setpoint: URIRef
    MAU: URIRef
    MDF: URIRef
    Mail_Room: URIRef
    Maintenance_Mode_Command: URIRef
    Maintenance_Required_Alarm: URIRef
    Majlis: URIRef
    Makeup_Air_Unit: URIRef
    Makeup_Water: URIRef
    Makeup_Water_Valve: URIRef
    Manual_Auto_Status: URIRef
    Massage_Room: URIRef
    Max_Air_Flow_Setpoint_Limit: URIRef
    Max_Air_Temperature_Setpoint: URIRef
    Max_Chilled_Water_Differential_Pressure_Setpoint_Limit: URIRef
    Max_Cooling_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Max_Cooling_Supply_Air_Flow_Setpoint_Limit: URIRef
    Max_Discharge_Air_Static_Pressure_Setpoint_Limit: URIRef
    Max_Discharge_Air_Temperature_Setpoint_Limit: URIRef
    Max_Frequency_Command: URIRef
    Max_Heating_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Max_Heating_Supply_Air_Flow_Setpoint_Limit: URIRef
    Max_Hot_Water_Differential_Pressure_Setpoint_Limit: URIRef
    Max_Limit: URIRef
    Max_Load_Setpoint: URIRef
    Max_Occupied_Cooling_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Max_Occupied_Cooling_Supply_Air_Flow_Setpoint_Limit: URIRef
    Max_Occupied_Heating_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Max_Occupied_Heating_Supply_Air_Flow_Setpoint_Limit: URIRef
    Max_Position_Setpoint_Limit: URIRef
    Max_Speed_Setpoint_Limit: URIRef
    Max_Static_Pressure_Setpoint_Limit: URIRef
    Max_Supply_Air_Static_Pressure_Setpoint_Limit: URIRef
    Max_Temperature_Setpoint_Limit: URIRef
    Max_Unoccupied_Cooling_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Max_Unoccupied_Cooling_Supply_Air_Flow_Setpoint_Limit: URIRef
    Max_Unoccupied_Heating_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Max_Unoccupied_Heating_Supply_Air_Flow_Setpoint_Limit: URIRef
    Max_Water_Level_Alarm: URIRef
    Max_Water_Temperature_Setpoint: URIRef
    Measurable: URIRef
    Mechanical_Room: URIRef
    Media_Hot_Desk: URIRef
    Media_Production_Room: URIRef
    Media_Room: URIRef
    Medical_Room: URIRef
    Medium_Temperature_Hot_Water_Differential_Pressure_Load_Shed_Reset_Status: URIRef
    Medium_Temperature_Hot_Water_Differential_Pressure_Load_Shed_Setpoint: URIRef
    Medium_Temperature_Hot_Water_Differential_Pressure_Load_Shed_Status: URIRef
    Medium_Temperature_Hot_Water_Differential_Pressure_Sensor: URIRef
    Medium_Temperature_Hot_Water_Differential_Pressure_Setpoint: URIRef
    Medium_Temperature_Hot_Water_Discharge_Temperature_High_Reset_Setpoint: URIRef
    Medium_Temperature_Hot_Water_Discharge_Temperature_Low_Reset_Setpoint: URIRef
    Medium_Temperature_Hot_Water_Return_Temperature_Sensor: URIRef
    Medium_Temperature_Hot_Water_Supply_Temperature_High_Reset_Setpoint: URIRef
    Medium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Setpoint: URIRef
    Medium_Temperature_Hot_Water_Supply_Temperature_Load_Shed_Status: URIRef
    Medium_Temperature_Hot_Water_Supply_Temperature_Low_Reset_Setpoint: URIRef
    Medium_Temperature_Hot_Water_Supply_Temperature_Sensor: URIRef
    Meter: URIRef
    Methane_Level_Sensor: URIRef
    Min_Air_Flow_Setpoint_Limit: URIRef
    Min_Air_Temperature_Setpoint: URIRef
    Min_Chilled_Water_Differential_Pressure_Setpoint_Limit: URIRef
    Min_Cooling_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Min_Cooling_Supply_Air_Flow_Setpoint_Limit: URIRef
    Min_Discharge_Air_Static_Pressure_Setpoint_Limit: URIRef
    Min_Discharge_Air_Temperature_Setpoint_Limit: URIRef
    Min_Fresh_Air_Setpoint_Limit: URIRef
    Min_Heating_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Min_Heating_Supply_Air_Flow_Setpoint_Limit: URIRef
    Min_Hot_Water_Differential_Pressure_Setpoint_Limit: URIRef
    Min_Limit: URIRef
    Min_Occupied_Cooling_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Min_Occupied_Cooling_Supply_Air_Flow_Setpoint_Limit: URIRef
    Min_Occupied_Heating_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Min_Occupied_Heating_Supply_Air_Flow_Setpoint_Limit: URIRef
    Min_Outside_Air_Flow_Setpoint_Limit: URIRef
    Min_Position_Setpoint_Limit: URIRef
    Min_Speed_Setpoint_Limit: URIRef
    Min_Static_Pressure_Setpoint_Limit: URIRef
    Min_Supply_Air_Static_Pressure_Setpoint_Limit: URIRef
    Min_Temperature_Setpoint_Limit: URIRef
    Min_Unoccupied_Cooling_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Min_Unoccupied_Cooling_Supply_Air_Flow_Setpoint_Limit: URIRef
    Min_Unoccupied_Heating_Discharge_Air_Flow_Setpoint_Limit: URIRef
    Min_Unoccupied_Heating_Supply_Air_Flow_Setpoint_Limit: URIRef
    Min_Water_Level_Alarm: URIRef
    Min_Water_Temperature_Setpoint: URIRef
    Mixed_Air: URIRef
    Mixed_Air_Filter: URIRef
    Mixed_Air_Flow_Sensor: URIRef
    Mixed_Air_Humidity_Sensor: URIRef
    Mixed_Air_Humidity_Setpoint: URIRef
    Mixed_Air_Temperature_Sensor: URIRef
    Mixed_Air_Temperature_Setpoint: URIRef
    Mixed_Damper: URIRef
    Mode_Command: URIRef
    Mode_Status: URIRef
    Motion_Sensor: URIRef
    Motor: URIRef
    Motor_Control_Center: URIRef
    Motor_Current_Sensor: URIRef
    Motor_Direction_Status: URIRef
    Motor_On_Off_Status: URIRef
    Motor_Speed_Sensor: URIRef
    Motor_Torque_Sensor: URIRef
    NO2_Level_Sensor: URIRef
    NVR: URIRef
    Natural_Gas: URIRef
    Natural_Gas_Boiler: URIRef
    Network_Video_Recorder: URIRef
    No_Water_Alarm: URIRef
    Noncondensing_Natural_Gas_Boiler: URIRef
    Occupancy_Command: URIRef
    Occupancy_Sensor: URIRef
    Occupancy_Status: URIRef
    Occupied_Air_Temperature_Setpoint: URIRef
    Occupied_Cooling_Discharge_Air_Flow_Setpoint: URIRef
    Occupied_Cooling_Supply_Air_Flow_Setpoint: URIRef
    Occupied_Cooling_Temperature_Deadband_Setpoint: URIRef
    Occupied_Discharge_Air_Flow_Setpoint: URIRef
    Occupied_Discharge_Air_Temperature_Setpoint: URIRef
    Occupied_Heating_Discharge_Air_Flow_Setpoint: URIRef
    Occupied_Heating_Supply_Air_Flow_Setpoint: URIRef
    Occupied_Heating_Temperature_Deadband_Setpoint: URIRef
    Occupied_Mode_Status: URIRef
    Occupied_Return_Air_Temperature_Setpoint: URIRef
    Occupied_Room_Air_Temperature_Setpoint: URIRef
    Occupied_Supply_Air_Flow_Setpoint: URIRef
    Occupied_Supply_Air_Temperature_Setpoint: URIRef
    Occupied_Zone_Air_Temperature_Setpoint: URIRef
    Off_Command: URIRef
    Off_Status: URIRef
    Office: URIRef
    Office_Kitchen: URIRef
    Oil: URIRef
    On_Command: URIRef
    On_Off_Command: URIRef
    On_Off_Status: URIRef
    On_Status: URIRef
    On_Timer_Sensor: URIRef
    Open_Close_Status: URIRef
    Open_Heating_Valve_Outside_Air_Temperature_Setpoint: URIRef
    Open_Office: URIRef
    Operating_Mode_Status: URIRef
    Outdoor_Area: URIRef
    Output_Frequency_Sensor: URIRef
    Output_Voltage_Sensor: URIRef
    Outside: URIRef
    Outside_Air: URIRef
    Outside_Air_CO2_Sensor: URIRef
    Outside_Air_CO_Sensor: URIRef
    Outside_Air_Dewpoint_Sensor: URIRef
    Outside_Air_Enthalpy_Sensor: URIRef
    Outside_Air_Flow_Sensor: URIRef
    Outside_Air_Flow_Setpoint: URIRef
    Outside_Air_Grains_Sensor: URIRef
    Outside_Air_Humidity_Sensor: URIRef
    Outside_Air_Humidity_Setpoint: URIRef
    Outside_Air_Lockout_Temperature_Differential_Parameter: URIRef
    Outside_Air_Lockout_Temperature_Setpoint: URIRef
    Outside_Air_Temperature_Enable_Differential_Sensor: URIRef
    Outside_Air_Temperature_High_Reset_Setpoint: URIRef
    Outside_Air_Temperature_Low_Reset_Setpoint: URIRef
    Outside_Air_Temperature_Sensor: URIRef
    Outside_Air_Temperature_Setpoint: URIRef
    Outside_Air_Wet_Bulb_Temperature_Sensor: URIRef
    Outside_Damper: URIRef
    Outside_Face_Surface_Temperature_Sensor: URIRef
    Outside_Face_Surface_Temperature_Setpoint: URIRef
    Outside_Illuminance_Sensor: URIRef
    Overload_Alarm: URIRef
    Overridden_Off_Status: URIRef
    Overridden_On_Status: URIRef
    Overridden_Status: URIRef
    Override_Command: URIRef
    Ozone_Level_Sensor: URIRef
    PAU: URIRef
    PID_Parameter: URIRef
    PIR_Sensor: URIRef
    PM10_Level_Sensor: URIRef
    PM10_Sensor: URIRef
    PM1_Level_Sensor: URIRef
    PM1_Sensor: URIRef
    PVT_Panel: URIRef
    PV_Array: URIRef
    PV_Current_Output_Sensor: URIRef
    PV_Generation_System: URIRef
    PV_Panel: URIRef
    Parameter: URIRef
    Parking_Level: URIRef
    Parking_Space: URIRef
    Parking_Structure: URIRef
    Particulate_Matter_Sensor: URIRef
    Passive_Chilled_Beam: URIRef
    Peak_Power_Demand_Sensor: URIRef
    Photovoltaic_Array: URIRef
    Photovoltaic_Current_Output_Sensor: URIRef
    Piezoelectric_Sensor: URIRef
    PlugStrip: URIRef
    Plumbing_Room: URIRef
    Point: URIRef
    Portfolio: URIRef
    Position_Command: URIRef
    Position_Limit: URIRef
    Position_Sensor: URIRef
    Potable_Water: URIRef
    Power_Alarm: URIRef
    Power_Loss_Alarm: URIRef
    Power_Sensor: URIRef
    Prayer_Room: URIRef
    Pre_Filter: URIRef
    Pre_Filter_Status: URIRef
    Preheat_Demand_Setpoint: URIRef
    Preheat_Discharge_Air_Temperature_Sensor: URIRef
    Preheat_Hot_Water_System: URIRef
    Preheat_Hot_Water_Valve: URIRef
    Preheat_Supply_Air_Temperature_Sensor: URIRef
    Pressure_Alarm: URIRef
    Pressure_Sensor: URIRef
    Pressure_Setpoint: URIRef
    Pressure_Status: URIRef
    Private_Office: URIRef
    Proportional_Band_Parameter: URIRef
    Proportional_Gain_Parameter: URIRef
    Pump: URIRef
    Pump_Command: URIRef
    Pump_On_Off_Status: URIRef
    Pump_Room: URIRef
    Pump_VFD: URIRef
    Quantity: URIRef
    RC_Panel: URIRef
    RTU: URIRef
    RVAV: URIRef
    Radiant_Ceiling_Panel: URIRef
    Radiant_Panel: URIRef
    Radiant_Panel_Temperature_Sensor: URIRef
    Radiant_Panel_Temperature_Setpoint: URIRef
    Radiation_Hot_Water_System: URIRef
    Radiator: URIRef
    Radioactivity_Concentration_Sensor: URIRef
    Radon_Concentration_Sensor: URIRef
    Rain_Duration_Sensor: URIRef
    Rain_Sensor: URIRef
    Rated_Speed_Setpoint: URIRef
    Reactive_Power_Sensor: URIRef
    Reception: URIRef
    Region: URIRef
    Reheat_Hot_Water_System: URIRef
    Reheat_Valve: URIRef
    Relative_Humidity_Sensor: URIRef
    Relief_Damper: URIRef
    Relief_Fan: URIRef
    Remotely_On_Off_Status: URIRef
    Reset_Command: URIRef
    Reset_Setpoint: URIRef
    Rest_Room: URIRef
    Restroom: URIRef
    Retail_Room: URIRef
    Return_Air: URIRef
    Return_Air_CO2_Sensor: URIRef
    Return_Air_CO2_Setpoint: URIRef
    Return_Air_CO_Sensor: URIRef
    Return_Air_Dewpoint_Sensor: URIRef
    Return_Air_Differential_Pressure_Sensor: URIRef
    Return_Air_Differential_Pressure_Setpoint: URIRef
    Return_Air_Enthalpy_Sensor: URIRef
    Return_Air_Filter: URIRef
    Return_Air_Flow_Sensor: URIRef
    Return_Air_Grains_Sensor: URIRef
    Return_Air_Humidity_Sensor: URIRef
    Return_Air_Humidity_Setpoint: URIRef
    Return_Air_Plenum: URIRef
    Return_Air_Temperature_Alarm: URIRef
    Return_Air_Temperature_High_Reset_Setpoint: URIRef
    Return_Air_Temperature_Low_Reset_Setpoint: URIRef
    Return_Air_Temperature_Sensor: URIRef
    Return_Air_Temperature_Setpoint: URIRef
    Return_Chilled_Water_Temperature_Setpoint: URIRef
    Return_Condenser_Water: URIRef
    Return_Condenser_Water_Flow_Sensor: URIRef
    Return_Condenser_Water_Temperature_Sensor: URIRef
    Return_Condenser_Water_Temperature_Setpoint: URIRef
    Return_Damper: URIRef
    Return_Fan: URIRef
    Return_Heating_Valve: URIRef
    Return_Hot_Water: URIRef
    Return_Hot_Water_Temperature_Setpoint: URIRef
    Return_Water: URIRef
    Return_Water_Flow_Sensor: URIRef
    Return_Water_Temperature_Sensor: URIRef
    Return_Water_Temperature_Setpoint: URIRef
    Riser: URIRef
    Rooftop: URIRef
    Rooftop_Unit: URIRef
    Room: URIRef
    Room_Air_Temperature_Setpoint: URIRef
    Run_Enable_Command: URIRef
    Run_Request_Status: URIRef
    Run_Status: URIRef
    Run_Time_Sensor: URIRef
    Safety_Equipment: URIRef
    Safety_Shower: URIRef
    Safety_System: URIRef
    Sash_Position_Sensor: URIRef
    Schedule_Temperature_Setpoint: URIRef
    Security_Equipment: URIRef
    Security_Service_Room: URIRef
    Sensor: URIRef
    Server_Room: URIRef
    Service_Room: URIRef
    Setpoint: URIRef
    Shading_System: URIRef
    Shared_Office: URIRef
    Short_Cycle_Alarm: URIRef
    Shower: URIRef
    Site: URIRef
    Smoke_Alarm: URIRef
    Smoke_Detection_Alarm: URIRef
    Solar_Azimuth_Angle_Sensor: URIRef
    Solar_Radiance_Sensor: URIRef
    Solar_Thermal_Collector: URIRef
    Solar_Zenith_Angle_Sensor: URIRef
    Solid: URIRef
    Space: URIRef
    Space_Heater: URIRef
    Speed_Reset_Command: URIRef
    Speed_Sensor: URIRef
    Speed_Setpoint: URIRef
    Speed_Setpoint_Limit: URIRef
    Speed_Status: URIRef
    Sports_Service_Room: URIRef
    Stage_Enable_Command: URIRef
    Stage_Riser: URIRef
    Stages_Status: URIRef
    Staircase: URIRef
    Standby_CRAC: URIRef
    Standby_Fan: URIRef
    Standby_Glycool_Unit_On_Off_Status: URIRef
    Standby_Load_Shed_Command: URIRef
    Standby_Unit_On_Off_Status: URIRef
    Start_Stop_Command: URIRef
    Start_Stop_Status: URIRef
    Static_Pressure_Deadband_Setpoint: URIRef
    Static_Pressure_Integral_Time_Parameter: URIRef
    Static_Pressure_Proportional_Band_Parameter: URIRef
    Static_Pressure_Sensor: URIRef
    Static_Pressure_Setpoint: URIRef
    Static_Pressure_Setpoint_Limit: URIRef
    Static_Pressure_Step_Parameter: URIRef
    Status: URIRef
    Steam: URIRef
    Steam_Baseboard_Radiator: URIRef
    Steam_Distribution: URIRef
    Steam_On_Off_Command: URIRef
    Steam_Radiator: URIRef
    Steam_System: URIRef
    Steam_Usage_Sensor: URIRef
    Steam_Valve: URIRef
    Step_Parameter: URIRef
    Storage_Room: URIRef
    Storey: URIRef
    Studio: URIRef
    Substance: URIRef
    Supply_Air: URIRef
    Supply_Air_Differential_Pressure_Sensor: URIRef
    Supply_Air_Differential_Pressure_Setpoint: URIRef
    Supply_Air_Duct_Pressure_Status: URIRef
    Supply_Air_Flow_Demand_Setpoint: URIRef
    Supply_Air_Flow_Sensor: URIRef
    Supply_Air_Flow_Setpoint: URIRef
    Supply_Air_Humidity_Sensor: URIRef
    Supply_Air_Humidity_Setpoint: URIRef
    Supply_Air_Integral_Gain_Parameter: URIRef
    Supply_Air_Plenum: URIRef
    Supply_Air_Proportional_Gain_Parameter: URIRef
    Supply_Air_Static_Pressure_Deadband_Setpoint: URIRef
    Supply_Air_Static_Pressure_Integral_Time_Parameter: URIRef
    Supply_Air_Static_Pressure_Proportional_Band_Parameter: URIRef
    Supply_Air_Static_Pressure_Sensor: URIRef
    Supply_Air_Static_Pressure_Setpoint: URIRef
    Supply_Air_Temperature_Alarm: URIRef
    Supply_Air_Temperature_Deadband_Setpoint: URIRef
    Supply_Air_Temperature_High_Reset_Setpoint: URIRef
    Supply_Air_Temperature_Low_Reset_Setpoint: URIRef
    Supply_Air_Temperature_Proportional_Band_Parameter: URIRef
    Supply_Air_Temperature_Reset_Differential_Setpoint: URIRef
    Supply_Air_Temperature_Sensor: URIRef
    Supply_Air_Temperature_Setpoint: URIRef
    Supply_Air_Temperature_Step_Parameter: URIRef
    Supply_Air_Velocity_Pressure_Sensor: URIRef
    Supply_Chilled_Water: URIRef
    Supply_Chilled_Water_Temperature_Setpoint: URIRef
    Supply_Condenser_Water: URIRef
    Supply_Condenser_Water_Flow_Sensor: URIRef
    Supply_Condenser_Water_Temperature_Sensor: URIRef
    Supply_Condenser_Water_Temperature_Setpoint: URIRef
    Supply_Fan: URIRef
    Supply_Hot_Water: URIRef
    Supply_Hot_Water_Temperature_Setpoint: URIRef
    Supply_Water: URIRef
    Supply_Water_Differential_Pressure_Deadband_Setpoint: URIRef
    Supply_Water_Differential_Pressure_Integral_Time_Parameter: URIRef
    Supply_Water_Differential_Pressure_Proportional_Band_Parameter: URIRef
    Supply_Water_Flow_Sensor: URIRef
    Supply_Water_Flow_Setpoint: URIRef
    Supply_Water_Temperature_Alarm: URIRef
    Supply_Water_Temperature_Deadband_Setpoint: URIRef
    Supply_Water_Temperature_Integral_Time_Parameter: URIRef
    Supply_Water_Temperature_Proportional_Band_Parameter: URIRef
    Supply_Water_Temperature_Setpoint: URIRef
    Surveillance_Camera: URIRef
    Switch: URIRef
    Switch_Room: URIRef
    Switchgear: URIRef
    System: URIRef
    System_Enable_Command: URIRef
    System_Shutdown_Status: URIRef
    System_Status: URIRef
    TABS_Panel: URIRef
    TETRA_Room: URIRef
    TVOC_Level_Sensor: URIRef
    TVOC_Sensor: URIRef
    Team_Room: URIRef
    Telecom_Room: URIRef
    Temperature_Alarm: URIRef
    Temperature_Deadband_Setpoint: URIRef
    Temperature_Differential_Reset_Setpoint: URIRef
    Temperature_High_Reset_Setpoint: URIRef
    Temperature_Low_Reset_Setpoint: URIRef
    Temperature_Parameter: URIRef
    Temperature_Sensor: URIRef
    Temperature_Setpoint: URIRef
    Temperature_Step_Parameter: URIRef
    Temperature_Tolerance_Parameter: URIRef
    Temporary_Occupancy_Status: URIRef
    Terminal_Unit: URIRef
    Thermal_Power_Meter: URIRef
    Thermal_Power_Sensor: URIRef
    Thermally_Activated_Building_System_Panel: URIRef
    Thermostat: URIRef
    Ticketing_Booth: URIRef
    Time_Parameter: URIRef
    Time_Setpoint: URIRef
    Tolerance_Parameter: URIRef
    Torque_Sensor: URIRef
    Touchpanel: URIRef
    Trace_Heat_Sensor: URIRef
    Transformer: URIRef
    Transformer_Room: URIRef
    Tunnel: URIRef
    Underfloor_Air_Plenum: URIRef
    Underfloor_Air_Plenum_Static_Pressure_Sensor: URIRef
    Underfloor_Air_Plenum_Static_Pressure_Setpoint: URIRef
    Underfloor_Air_Temperature_Sensor: URIRef
    Unit_Failure_Alarm: URIRef
    Unoccupied_Air_Temperature_Cooling_Setpoint: URIRef
    Unoccupied_Air_Temperature_Heating_Setpoint: URIRef
    Unoccupied_Air_Temperature_Setpoint: URIRef
    Unoccupied_Cooling_Discharge_Air_Flow_Setpoint: URIRef
    Unoccupied_Discharge_Air_Temperature_Setpoint: URIRef
    Unoccupied_Load_Shed_Command: URIRef
    Unoccupied_Return_Air_Temperature_Setpoint: URIRef
    Unoccupied_Room_Air_Temperature_Setpoint: URIRef
    Unoccupied_Supply_Air_Temperature_Setpoint: URIRef
    Unoccupied_Zone_Air_Temperature_Setpoint: URIRef
    Usage_Sensor: URIRef
    VAV: URIRef
    VFD: URIRef
    VFD_Enable_Command: URIRef
    Valve: URIRef
    Valve_Command: URIRef
    Valve_Position_Sensor: URIRef
    Variable_Air_Volume_Box: URIRef
    Variable_Air_Volume_Box_With_Reheat: URIRef
    Variable_Frequency_Drive: URIRef
    Velocity_Pressure_Sensor: URIRef
    Velocity_Pressure_Setpoint: URIRef
    Vent_Operating_Mode_Status: URIRef
    Ventilation_Air_Flow_Ratio_Limit: URIRef
    Ventilation_Air_System: URIRef
    Vertical_Space: URIRef
    Video_Intercom: URIRef
    Video_Surveillance_Equipment: URIRef
    Visitor_Lobby: URIRef
    Voltage_Imbalance_Sensor: URIRef
    Voltage_Sensor: URIRef
    Wardrobe: URIRef
    Warm_Cool_Adjust_Sensor: URIRef
    Warmest_Zone_Air_Temperature_Sensor: URIRef
    Waste_Storage: URIRef
    Water: URIRef
    Water_Alarm: URIRef
    Water_Differential_Pressure_Setpoint: URIRef
    Water_Differential_Temperature_Sensor: URIRef
    Water_Differential_Temperature_Setpoint: URIRef
    Water_Distribution: URIRef
    Water_Flow_Sensor: URIRef
    Water_Flow_Setpoint: URIRef
    Water_Heater: URIRef
    Water_Level_Alarm: URIRef
    Water_Level_Sensor: URIRef
    Water_Loop: URIRef
    Water_Loss_Alarm: URIRef
    Water_Meter: URIRef
    Water_Pump: URIRef
    Water_System: URIRef
    Water_Tank: URIRef
    Water_Temperature_Alarm: URIRef
    Water_Temperature_Sensor: URIRef
    Water_Temperature_Setpoint: URIRef
    Water_Usage_Sensor: URIRef
    Water_Valve: URIRef
    Weather_Station: URIRef
    Wind_Direction_Sensor: URIRef
    Wind_Speed_Sensor: URIRef
    Wing: URIRef
    Workshop: URIRef
    Zone: URIRef
    Zone_Air: URIRef
    Zone_Air_Cooling_Temperature_Setpoint: URIRef
    Zone_Air_Dewpoint_Sensor: URIRef
    Zone_Air_Heating_Temperature_Setpoint: URIRef
    Zone_Air_Humidity_Sensor: URIRef
    Zone_Air_Humidity_Setpoint: URIRef
    Zone_Air_Temperature_Sensor: URIRef
    Zone_Air_Temperature_Setpoint: URIRef
    Zone_Standby_Load_Shed_Command: URIRef
    Zone_Unoccupied_Load_Shed_Command: URIRef
    feeds: URIRef
    feedsAir: URIRef
    hasAddress: URIRef
    hasAssociatedTag: URIRef
    hasInputSubstance: URIRef
    hasLocation: URIRef
    hasOutputSubstance: URIRef
    hasPart: URIRef
    hasPoint: URIRef
    hasQUDTReference: URIRef
    hasTag: URIRef
    hasTimeseriesId: URIRef
    hasUnit: URIRef
    isAssociatedWith: URIRef
    isFedBy: URIRef
    isLocationOf: URIRef
    isMeasuredBy: URIRef
    isPartOf: URIRef
    isPointOf: URIRef
    isRegulatedBy: URIRef
    isTagOf: URIRef
    latitude: URIRef
    longitude: URIRef
    measures: URIRef
    regulates: URIRef
    storedAt: URIRef
    timeseries: URIRef
    value: URIRef
    aggregate: URIRef
    area: URIRef
    azimuth: URIRef
    buildingPrimaryFunction: URIRef
    buildingThermalTransmittance: URIRef
    conversionEfficiency: URIRef
    coolingCapacity: URIRef
    coordinates: URIRef
    currentFlowType: URIRef
    electricalPhaseCount: URIRef
    electricalPhases: URIRef
    grossArea: URIRef
    measuredModuleConversionEfficiency: URIRef
    measuredPowerOutput: URIRef
    netArea: URIRef
    operationalStage: URIRef
    operationalStageCount: URIRef
    panelArea: URIRef
    powerComplexity: URIRef
    powerFlow: URIRef
    ratedModuleConversionEfficiency: URIRef
    ratedPowerOutput: URIRef
    temperatureCoefficientofPmax: URIRef
    thermalTransmittance: URIRef
    tilt: URIRef
    volume: URIRef
    yearBuilt: URIRef
