from rdflib.namespace import DefinedNamespace as DefinedNamespace, Namespace as Namespace
from rdflib.term import URIRef as URIRef

class SDO(DefinedNamespace):
    AMRadioChannel: URIRef
    APIReference: URIRef
    Abdomen: URIRef
    AboutPage: URIRef
    AcceptAction: URIRef
    Accommodation: URIRef
    AccountingService: URIRef
    AchieveAction: URIRef
    Action: URIRef
    ActionAccessSpecification: URIRef
    ActionStatusType: URIRef
    ActivateAction: URIRef
    ActivationFee: URIRef
    ActiveActionStatus: URIRef
    ActiveNotRecruiting: URIRef
    AddAction: URIRef
    AdministrativeArea: URIRef
    AdultEntertainment: URIRef
    AdvertiserContentArticle: URIRef
    AerobicActivity: URIRef
    AggregateOffer: URIRef
    AggregateRating: URIRef
    AgreeAction: URIRef
    Airline: URIRef
    Airport: URIRef
    AlbumRelease: URIRef
    AlignmentObject: URIRef
    AllWheelDriveConfiguration: URIRef
    AllergiesHealthAspect: URIRef
    AllocateAction: URIRef
    AmpStory: URIRef
    AmusementPark: URIRef
    AnaerobicActivity: URIRef
    AnalysisNewsArticle: URIRef
    AnatomicalStructure: URIRef
    AnatomicalSystem: URIRef
    Anesthesia: URIRef
    AnimalShelter: URIRef
    Answer: URIRef
    Apartment: URIRef
    ApartmentComplex: URIRef
    Appearance: URIRef
    AppendAction: URIRef
    ApplyAction: URIRef
    ApprovedIndication: URIRef
    Aquarium: URIRef
    ArchiveComponent: URIRef
    ArchiveOrganization: URIRef
    ArriveAction: URIRef
    ArtGallery: URIRef
    Artery: URIRef
    Article: URIRef
    AskAction: URIRef
    AskPublicNewsArticle: URIRef
    AssessAction: URIRef
    AssignAction: URIRef
    Atlas: URIRef
    Attorney: URIRef
    Audience: URIRef
    AudioObject: URIRef
    AudioObjectSnapshot: URIRef
    Audiobook: URIRef
    AudiobookFormat: URIRef
    AuthoritativeLegalValue: URIRef
    AuthorizeAction: URIRef
    AutoBodyShop: URIRef
    AutoDealer: URIRef
    AutoPartsStore: URIRef
    AutoRental: URIRef
    AutoRepair: URIRef
    AutoWash: URIRef
    AutomatedTeller: URIRef
    AutomotiveBusiness: URIRef
    Ayurvedic: URIRef
    BackOrder: URIRef
    BackgroundNewsArticle: URIRef
    Bacteria: URIRef
    Bakery: URIRef
    Balance: URIRef
    BankAccount: URIRef
    BankOrCreditUnion: URIRef
    BarOrPub: URIRef
    Barcode: URIRef
    BasicIncome: URIRef
    Beach: URIRef
    BeautySalon: URIRef
    BedAndBreakfast: URIRef
    BedDetails: URIRef
    BedType: URIRef
    BefriendAction: URIRef
    BenefitsHealthAspect: URIRef
    BikeStore: URIRef
    BioChemEntity: URIRef
    Blog: URIRef
    BlogPosting: URIRef
    BloodTest: URIRef
    BoardingPolicyType: URIRef
    BoatReservation: URIRef
    BoatTerminal: URIRef
    BoatTrip: URIRef
    BodyMeasurementArm: URIRef
    BodyMeasurementBust: URIRef
    BodyMeasurementChest: URIRef
    BodyMeasurementFoot: URIRef
    BodyMeasurementHand: URIRef
    BodyMeasurementHead: URIRef
    BodyMeasurementHeight: URIRef
    BodyMeasurementHips: URIRef
    BodyMeasurementInsideLeg: URIRef
    BodyMeasurementNeck: URIRef
    BodyMeasurementTypeEnumeration: URIRef
    BodyMeasurementUnderbust: URIRef
    BodyMeasurementWaist: URIRef
    BodyMeasurementWeight: URIRef
    BodyOfWater: URIRef
    Bone: URIRef
    Book: URIRef
    BookFormatType: URIRef
    BookSeries: URIRef
    BookStore: URIRef
    BookmarkAction: URIRef
    Boolean: URIRef
    BorrowAction: URIRef
    BowlingAlley: URIRef
    BrainStructure: URIRef
    Brand: URIRef
    BreadcrumbList: URIRef
    Brewery: URIRef
    Bridge: URIRef
    BroadcastChannel: URIRef
    BroadcastEvent: URIRef
    BroadcastFrequencySpecification: URIRef
    BroadcastRelease: URIRef
    BroadcastService: URIRef
    BrokerageAccount: URIRef
    BuddhistTemple: URIRef
    BusOrCoach: URIRef
    BusReservation: URIRef
    BusStation: URIRef
    BusStop: URIRef
    BusTrip: URIRef
    BusinessAudience: URIRef
    BusinessEntityType: URIRef
    BusinessEvent: URIRef
    BusinessFunction: URIRef
    BusinessSupport: URIRef
    BuyAction: URIRef
    CDCPMDRecord: URIRef
    CDFormat: URIRef
    CT: URIRef
    CableOrSatelliteService: URIRef
    CafeOrCoffeeShop: URIRef
    Campground: URIRef
    CampingPitch: URIRef
    Canal: URIRef
    CancelAction: URIRef
    Car: URIRef
    CarUsageType: URIRef
    Cardiovascular: URIRef
    CardiovascularExam: URIRef
    CaseSeries: URIRef
    Casino: URIRef
    CassetteFormat: URIRef
    CategoryCode: URIRef
    CategoryCodeSet: URIRef
    CatholicChurch: URIRef
    CausesHealthAspect: URIRef
    Cemetery: URIRef
    Chapter: URIRef
    CharitableIncorporatedOrganization: URIRef
    CheckAction: URIRef
    CheckInAction: URIRef
    CheckOutAction: URIRef
    CheckoutPage: URIRef
    ChemicalSubstance: URIRef
    ChildCare: URIRef
    ChildrensEvent: URIRef
    Chiropractic: URIRef
    ChooseAction: URIRef
    Church: URIRef
    City: URIRef
    CityHall: URIRef
    CivicStructure: URIRef
    Claim: URIRef
    ClaimReview: URIRef
    Class: URIRef
    CleaningFee: URIRef
    Clinician: URIRef
    Clip: URIRef
    ClothingStore: URIRef
    CoOp: URIRef
    Code: URIRef
    CohortStudy: URIRef
    Collection: URIRef
    CollectionPage: URIRef
    CollegeOrUniversity: URIRef
    ComedyClub: URIRef
    ComedyEvent: URIRef
    ComicCoverArt: URIRef
    ComicIssue: URIRef
    ComicSeries: URIRef
    ComicStory: URIRef
    Comment: URIRef
    CommentAction: URIRef
    CommentPermission: URIRef
    CommunicateAction: URIRef
    CommunityHealth: URIRef
    CompilationAlbum: URIRef
    CompleteDataFeed: URIRef
    Completed: URIRef
    CompletedActionStatus: URIRef
    CompoundPriceSpecification: URIRef
    ComputerLanguage: URIRef
    ComputerStore: URIRef
    ConfirmAction: URIRef
    Consortium: URIRef
    ConsumeAction: URIRef
    ContactPage: URIRef
    ContactPoint: URIRef
    ContactPointOption: URIRef
    ContagiousnessHealthAspect: URIRef
    Continent: URIRef
    ControlAction: URIRef
    ConvenienceStore: URIRef
    Conversation: URIRef
    CookAction: URIRef
    Corporation: URIRef
    CorrectionComment: URIRef
    Country: URIRef
    Course: URIRef
    CourseInstance: URIRef
    Courthouse: URIRef
    CoverArt: URIRef
    CovidTestingFacility: URIRef
    CreateAction: URIRef
    CreativeWork: URIRef
    CreativeWorkSeason: URIRef
    CreativeWorkSeries: URIRef
    CreditCard: URIRef
    Crematorium: URIRef
    CriticReview: URIRef
    CrossSectional: URIRef
    CssSelectorType: URIRef
    CurrencyConversionService: URIRef
    DDxElement: URIRef
    DJMixAlbum: URIRef
    DVDFormat: URIRef
    DamagedCondition: URIRef
    DanceEvent: URIRef
    DanceGroup: URIRef
    DataCatalog: URIRef
    DataDownload: URIRef
    DataFeed: URIRef
    DataFeedItem: URIRef
    DataType: URIRef
    Dataset: URIRef
    Date: URIRef
    DateTime: URIRef
    DatedMoneySpecification: URIRef
    DayOfWeek: URIRef
    DaySpa: URIRef
    DeactivateAction: URIRef
    DecontextualizedContent: URIRef
    DefenceEstablishment: URIRef
    DefinedRegion: URIRef
    DefinedTerm: URIRef
    DefinedTermSet: URIRef
    DefinitiveLegalValue: URIRef
    DeleteAction: URIRef
    DeliveryChargeSpecification: URIRef
    DeliveryEvent: URIRef
    DeliveryMethod: URIRef
    DeliveryTimeSettings: URIRef
    Demand: URIRef
    DemoAlbum: URIRef
    Dentist: URIRef
    Dentistry: URIRef
    DepartAction: URIRef
    DepartmentStore: URIRef
    DepositAccount: URIRef
    Dermatologic: URIRef
    Dermatology: URIRef
    DiabeticDiet: URIRef
    Diagnostic: URIRef
    DiagnosticLab: URIRef
    DiagnosticProcedure: URIRef
    Diet: URIRef
    DietNutrition: URIRef
    DietarySupplement: URIRef
    DigitalAudioTapeFormat: URIRef
    DigitalDocument: URIRef
    DigitalDocumentPermission: URIRef
    DigitalDocumentPermissionType: URIRef
    DigitalFormat: URIRef
    DisabilitySupport: URIRef
    DisagreeAction: URIRef
    Discontinued: URIRef
    DiscoverAction: URIRef
    DiscussionForumPosting: URIRef
    DislikeAction: URIRef
    Distance: URIRef
    DistanceFee: URIRef
    Distillery: URIRef
    DonateAction: URIRef
    DoseSchedule: URIRef
    DoubleBlindedTrial: URIRef
    DownloadAction: URIRef
    Downpayment: URIRef
    DrawAction: URIRef
    Drawing: URIRef
    DrinkAction: URIRef
    DriveWheelConfigurationValue: URIRef
    DrivingSchoolVehicleUsage: URIRef
    Drug: URIRef
    DrugClass: URIRef
    DrugCost: URIRef
    DrugCostCategory: URIRef
    DrugLegalStatus: URIRef
    DrugPregnancyCategory: URIRef
    DrugPrescriptionStatus: URIRef
    DrugStrength: URIRef
    DryCleaningOrLaundry: URIRef
    Duration: URIRef
    EBook: URIRef
    EPRelease: URIRef
    EUEnergyEfficiencyCategoryA: URIRef
    EUEnergyEfficiencyCategoryA1Plus: URIRef
    EUEnergyEfficiencyCategoryA2Plus: URIRef
    EUEnergyEfficiencyCategoryA3Plus: URIRef
    EUEnergyEfficiencyCategoryB: URIRef
    EUEnergyEfficiencyCategoryC: URIRef
    EUEnergyEfficiencyCategoryD: URIRef
    EUEnergyEfficiencyCategoryE: URIRef
    EUEnergyEfficiencyCategoryF: URIRef
    EUEnergyEfficiencyCategoryG: URIRef
    EUEnergyEfficiencyEnumeration: URIRef
    Ear: URIRef
    EatAction: URIRef
    EditedOrCroppedContent: URIRef
    EducationEvent: URIRef
    EducationalAudience: URIRef
    EducationalOccupationalCredential: URIRef
    EducationalOccupationalProgram: URIRef
    EducationalOrganization: URIRef
    EffectivenessHealthAspect: URIRef
    Electrician: URIRef
    ElectronicsStore: URIRef
    ElementarySchool: URIRef
    EmailMessage: URIRef
    Embassy: URIRef
    Emergency: URIRef
    EmergencyService: URIRef
    EmployeeRole: URIRef
    EmployerAggregateRating: URIRef
    EmployerReview: URIRef
    EmploymentAgency: URIRef
    Endocrine: URIRef
    EndorseAction: URIRef
    EndorsementRating: URIRef
    Energy: URIRef
    EnergyConsumptionDetails: URIRef
    EnergyEfficiencyEnumeration: URIRef
    EnergyStarCertified: URIRef
    EnergyStarEnergyEfficiencyEnumeration: URIRef
    EngineSpecification: URIRef
    EnrollingByInvitation: URIRef
    EntertainmentBusiness: URIRef
    EntryPoint: URIRef
    Enumeration: URIRef
    Episode: URIRef
    Event: URIRef
    EventAttendanceModeEnumeration: URIRef
    EventCancelled: URIRef
    EventMovedOnline: URIRef
    EventPostponed: URIRef
    EventRescheduled: URIRef
    EventReservation: URIRef
    EventScheduled: URIRef
    EventSeries: URIRef
    EventStatusType: URIRef
    EventVenue: URIRef
    EvidenceLevelA: URIRef
    EvidenceLevelB: URIRef
    EvidenceLevelC: URIRef
    ExchangeRateSpecification: URIRef
    ExchangeRefund: URIRef
    ExerciseAction: URIRef
    ExerciseGym: URIRef
    ExercisePlan: URIRef
    ExhibitionEvent: URIRef
    Eye: URIRef
    FAQPage: URIRef
    FDAcategoryA: URIRef
    FDAcategoryB: URIRef
    FDAcategoryC: URIRef
    FDAcategoryD: URIRef
    FDAcategoryX: URIRef
    FDAnotEvaluated: URIRef
    FMRadioChannel: URIRef
    FailedActionStatus: URIRef
    FastFoodRestaurant: URIRef
    Female: URIRef
    Festival: URIRef
    FilmAction: URIRef
    FinancialProduct: URIRef
    FinancialService: URIRef
    FindAction: URIRef
    FireStation: URIRef
    Flexibility: URIRef
    Flight: URIRef
    FlightReservation: URIRef
    Float: URIRef
    FloorPlan: URIRef
    Florist: URIRef
    FollowAction: URIRef
    FoodEstablishment: URIRef
    FoodEstablishmentReservation: URIRef
    FoodEvent: URIRef
    FoodService: URIRef
    FourWheelDriveConfiguration: URIRef
    FreeReturn: URIRef
    Friday: URIRef
    FrontWheelDriveConfiguration: URIRef
    FullRefund: URIRef
    FundingAgency: URIRef
    FundingScheme: URIRef
    Fungus: URIRef
    FurnitureStore: URIRef
    Game: URIRef
    GamePlayMode: URIRef
    GameServer: URIRef
    GameServerStatus: URIRef
    GardenStore: URIRef
    GasStation: URIRef
    Gastroenterologic: URIRef
    GatedResidenceCommunity: URIRef
    GenderType: URIRef
    Gene: URIRef
    GeneralContractor: URIRef
    Genetic: URIRef
    Genitourinary: URIRef
    GeoCircle: URIRef
    GeoCoordinates: URIRef
    GeoShape: URIRef
    GeospatialGeometry: URIRef
    Geriatric: URIRef
    GettingAccessHealthAspect: URIRef
    GiveAction: URIRef
    GlutenFreeDiet: URIRef
    GolfCourse: URIRef
    GovernmentBenefitsType: URIRef
    GovernmentBuilding: URIRef
    GovernmentOffice: URIRef
    GovernmentOrganization: URIRef
    GovernmentPermit: URIRef
    GovernmentService: URIRef
    Grant: URIRef
    GraphicNovel: URIRef
    GroceryStore: URIRef
    GroupBoardingPolicy: URIRef
    Guide: URIRef
    Gynecologic: URIRef
    HVACBusiness: URIRef
    Hackathon: URIRef
    HairSalon: URIRef
    HalalDiet: URIRef
    Hardcover: URIRef
    HardwareStore: URIRef
    Head: URIRef
    HealthAndBeautyBusiness: URIRef
    HealthAspectEnumeration: URIRef
    HealthCare: URIRef
    HealthClub: URIRef
    HealthInsurancePlan: URIRef
    HealthPlanCostSharingSpecification: URIRef
    HealthPlanFormulary: URIRef
    HealthPlanNetwork: URIRef
    HealthTopicContent: URIRef
    HearingImpairedSupported: URIRef
    Hematologic: URIRef
    HighSchool: URIRef
    HinduDiet: URIRef
    HinduTemple: URIRef
    HobbyShop: URIRef
    HomeAndConstructionBusiness: URIRef
    HomeGoodsStore: URIRef
    Homeopathic: URIRef
    Hospital: URIRef
    Hostel: URIRef
    Hotel: URIRef
    HotelRoom: URIRef
    House: URIRef
    HousePainter: URIRef
    HowItWorksHealthAspect: URIRef
    HowOrWhereHealthAspect: URIRef
    HowTo: URIRef
    HowToDirection: URIRef
    HowToItem: URIRef
    HowToSection: URIRef
    HowToStep: URIRef
    HowToSupply: URIRef
    HowToTip: URIRef
    HowToTool: URIRef
    HyperToc: URIRef
    HyperTocEntry: URIRef
    IceCreamShop: URIRef
    IgnoreAction: URIRef
    ImageGallery: URIRef
    ImageObject: URIRef
    ImageObjectSnapshot: URIRef
    ImagingTest: URIRef
    InForce: URIRef
    InStock: URIRef
    InStoreOnly: URIRef
    IndividualProduct: URIRef
    Infectious: URIRef
    InfectiousAgentClass: URIRef
    InfectiousDisease: URIRef
    InformAction: URIRef
    IngredientsHealthAspect: URIRef
    InsertAction: URIRef
    InstallAction: URIRef
    Installment: URIRef
    InsuranceAgency: URIRef
    Intangible: URIRef
    Integer: URIRef
    InteractAction: URIRef
    InteractionCounter: URIRef
    InternationalTrial: URIRef
    InternetCafe: URIRef
    InvestmentFund: URIRef
    InvestmentOrDeposit: URIRef
    InviteAction: URIRef
    Invoice: URIRef
    InvoicePrice: URIRef
    ItemAvailability: URIRef
    ItemList: URIRef
    ItemListOrderAscending: URIRef
    ItemListOrderDescending: URIRef
    ItemListOrderType: URIRef
    ItemListUnordered: URIRef
    ItemPage: URIRef
    JewelryStore: URIRef
    JobPosting: URIRef
    JoinAction: URIRef
    Joint: URIRef
    KosherDiet: URIRef
    LaboratoryScience: URIRef
    LakeBodyOfWater: URIRef
    Landform: URIRef
    LandmarksOrHistoricalBuildings: URIRef
    Language: URIRef
    LaserDiscFormat: URIRef
    LearningResource: URIRef
    LeaveAction: URIRef
    LeftHandDriving: URIRef
    LegalForceStatus: URIRef
    LegalService: URIRef
    LegalValueLevel: URIRef
    Legislation: URIRef
    LegislationObject: URIRef
    LegislativeBuilding: URIRef
    LeisureTimeActivity: URIRef
    LendAction: URIRef
    Library: URIRef
    LibrarySystem: URIRef
    LifestyleModification: URIRef
    Ligament: URIRef
    LikeAction: URIRef
    LimitedAvailability: URIRef
    LimitedByGuaranteeCharity: URIRef
    LinkRole: URIRef
    LiquorStore: URIRef
    ListItem: URIRef
    ListPrice: URIRef
    ListenAction: URIRef
    LiteraryEvent: URIRef
    LiveAlbum: URIRef
    LiveBlogPosting: URIRef
    LivingWithHealthAspect: URIRef
    LoanOrCredit: URIRef
    LocalBusiness: URIRef
    LocationFeatureSpecification: URIRef
    LockerDelivery: URIRef
    Locksmith: URIRef
    LodgingBusiness: URIRef
    LodgingReservation: URIRef
    Longitudinal: URIRef
    LoseAction: URIRef
    LowCalorieDiet: URIRef
    LowFatDiet: URIRef
    LowLactoseDiet: URIRef
    LowSaltDiet: URIRef
    Lung: URIRef
    LymphaticVessel: URIRef
    MRI: URIRef
    MSRP: URIRef
    Male: URIRef
    Manuscript: URIRef
    Map: URIRef
    MapCategoryType: URIRef
    MarryAction: URIRef
    Mass: URIRef
    MathSolver: URIRef
    MaximumDoseSchedule: URIRef
    MayTreatHealthAspect: URIRef
    MeasurementTypeEnumeration: URIRef
    MediaGallery: URIRef
    MediaManipulationRatingEnumeration: URIRef
    MediaObject: URIRef
    MediaReview: URIRef
    MediaReviewItem: URIRef
    MediaSubscription: URIRef
    MedicalAudience: URIRef
    MedicalAudienceType: URIRef
    MedicalBusiness: URIRef
    MedicalCause: URIRef
    MedicalClinic: URIRef
    MedicalCode: URIRef
    MedicalCondition: URIRef
    MedicalConditionStage: URIRef
    MedicalContraindication: URIRef
    MedicalDevice: URIRef
    MedicalDevicePurpose: URIRef
    MedicalEntity: URIRef
    MedicalEnumeration: URIRef
    MedicalEvidenceLevel: URIRef
    MedicalGuideline: URIRef
    MedicalGuidelineContraindication: URIRef
    MedicalGuidelineRecommendation: URIRef
    MedicalImagingTechnique: URIRef
    MedicalIndication: URIRef
    MedicalIntangible: URIRef
    MedicalObservationalStudy: URIRef
    MedicalObservationalStudyDesign: URIRef
    MedicalOrganization: URIRef
    MedicalProcedure: URIRef
    MedicalProcedureType: URIRef
    MedicalResearcher: URIRef
    MedicalRiskCalculator: URIRef
    MedicalRiskEstimator: URIRef
    MedicalRiskFactor: URIRef
    MedicalRiskScore: URIRef
    MedicalScholarlyArticle: URIRef
    MedicalSign: URIRef
    MedicalSignOrSymptom: URIRef
    MedicalSpecialty: URIRef
    MedicalStudy: URIRef
    MedicalStudyStatus: URIRef
    MedicalSymptom: URIRef
    MedicalTest: URIRef
    MedicalTestPanel: URIRef
    MedicalTherapy: URIRef
    MedicalTrial: URIRef
    MedicalTrialDesign: URIRef
    MedicalWebPage: URIRef
    MedicineSystem: URIRef
    MeetingRoom: URIRef
    MensClothingStore: URIRef
    Menu: URIRef
    MenuItem: URIRef
    MenuSection: URIRef
    MerchantReturnEnumeration: URIRef
    MerchantReturnFiniteReturnWindow: URIRef
    MerchantReturnNotPermitted: URIRef
    MerchantReturnPolicy: URIRef
    MerchantReturnPolicySeasonalOverride: URIRef
    MerchantReturnUnlimitedWindow: URIRef
    MerchantReturnUnspecified: URIRef
    Message: URIRef
    MiddleSchool: URIRef
    Midwifery: URIRef
    MinimumAdvertisedPrice: URIRef
    MisconceptionsHealthAspect: URIRef
    MixedEventAttendanceMode: URIRef
    MixtapeAlbum: URIRef
    MobileApplication: URIRef
    MobilePhoneStore: URIRef
    MolecularEntity: URIRef
    Monday: URIRef
    MonetaryAmount: URIRef
    MonetaryAmountDistribution: URIRef
    MonetaryGrant: URIRef
    MoneyTransfer: URIRef
    MortgageLoan: URIRef
    Mosque: URIRef
    Motel: URIRef
    Motorcycle: URIRef
    MotorcycleDealer: URIRef
    MotorcycleRepair: URIRef
    MotorizedBicycle: URIRef
    Mountain: URIRef
    MoveAction: URIRef
    Movie: URIRef
    MovieClip: URIRef
    MovieRentalStore: URIRef
    MovieSeries: URIRef
    MovieTheater: URIRef
    MovingCompany: URIRef
    MultiCenterTrial: URIRef
    MultiPlayer: URIRef
    MulticellularParasite: URIRef
    Muscle: URIRef
    Musculoskeletal: URIRef
    MusculoskeletalExam: URIRef
    Museum: URIRef
    MusicAlbum: URIRef
    MusicAlbumProductionType: URIRef
    MusicAlbumReleaseType: URIRef
    MusicComposition: URIRef
    MusicEvent: URIRef
    MusicGroup: URIRef
    MusicPlaylist: URIRef
    MusicRecording: URIRef
    MusicRelease: URIRef
    MusicReleaseFormatType: URIRef
    MusicStore: URIRef
    MusicVenue: URIRef
    MusicVideoObject: URIRef
    NGO: URIRef
    NLNonprofitType: URIRef
    NailSalon: URIRef
    Neck: URIRef
    Nerve: URIRef
    Neuro: URIRef
    Neurologic: URIRef
    NewCondition: URIRef
    NewsArticle: URIRef
    NewsMediaOrganization: URIRef
    Newspaper: URIRef
    NightClub: URIRef
    NoninvasiveProcedure: URIRef
    Nonprofit501a: URIRef
    Nonprofit501c1: URIRef
    Nonprofit501c10: URIRef
    Nonprofit501c11: URIRef
    Nonprofit501c12: URIRef
    Nonprofit501c13: URIRef
    Nonprofit501c14: URIRef
    Nonprofit501c15: URIRef
    Nonprofit501c16: URIRef
    Nonprofit501c17: URIRef
    Nonprofit501c18: URIRef
    Nonprofit501c19: URIRef
    Nonprofit501c2: URIRef
    Nonprofit501c20: URIRef
    Nonprofit501c21: URIRef
    Nonprofit501c22: URIRef
    Nonprofit501c23: URIRef
    Nonprofit501c24: URIRef
    Nonprofit501c25: URIRef
    Nonprofit501c26: URIRef
    Nonprofit501c27: URIRef
    Nonprofit501c28: URIRef
    Nonprofit501c3: URIRef
    Nonprofit501c4: URIRef
    Nonprofit501c5: URIRef
    Nonprofit501c6: URIRef
    Nonprofit501c7: URIRef
    Nonprofit501c8: URIRef
    Nonprofit501c9: URIRef
    Nonprofit501d: URIRef
    Nonprofit501e: URIRef
    Nonprofit501f: URIRef
    Nonprofit501k: URIRef
    Nonprofit501n: URIRef
    Nonprofit501q: URIRef
    Nonprofit527: URIRef
    NonprofitANBI: URIRef
    NonprofitSBBI: URIRef
    NonprofitType: URIRef
    Nose: URIRef
    NotInForce: URIRef
    NotYetRecruiting: URIRef
    Notary: URIRef
    NoteDigitalDocument: URIRef
    Number: URIRef
    Nursing: URIRef
    NutritionInformation: URIRef
    OTC: URIRef
    Observation: URIRef
    Observational: URIRef
    Obstetric: URIRef
    Occupation: URIRef
    OccupationalActivity: URIRef
    OccupationalExperienceRequirements: URIRef
    OccupationalTherapy: URIRef
    OceanBodyOfWater: URIRef
    Offer: URIRef
    OfferCatalog: URIRef
    OfferForLease: URIRef
    OfferForPurchase: URIRef
    OfferItemCondition: URIRef
    OfferShippingDetails: URIRef
    OfficeEquipmentStore: URIRef
    OfficialLegalValue: URIRef
    OfflineEventAttendanceMode: URIRef
    OfflinePermanently: URIRef
    OfflineTemporarily: URIRef
    OnDemandEvent: URIRef
    OnSitePickup: URIRef
    Oncologic: URIRef
    OneTimePayments: URIRef
    Online: URIRef
    OnlineEventAttendanceMode: URIRef
    OnlineFull: URIRef
    OnlineOnly: URIRef
    OpenTrial: URIRef
    OpeningHoursSpecification: URIRef
    OpinionNewsArticle: URIRef
    Optician: URIRef
    Optometric: URIRef
    Order: URIRef
    OrderAction: URIRef
    OrderCancelled: URIRef
    OrderDelivered: URIRef
    OrderInTransit: URIRef
    OrderItem: URIRef
    OrderPaymentDue: URIRef
    OrderPickupAvailable: URIRef
    OrderProblem: URIRef
    OrderProcessing: URIRef
    OrderReturned: URIRef
    OrderStatus: URIRef
    Organization: URIRef
    OrganizationRole: URIRef
    OrganizeAction: URIRef
    OriginalMediaContent: URIRef
    OriginalShippingFees: URIRef
    Osteopathic: URIRef
    Otolaryngologic: URIRef
    OutOfStock: URIRef
    OutletStore: URIRef
    OverviewHealthAspect: URIRef
    OwnershipInfo: URIRef
    PET: URIRef
    PaidLeave: URIRef
    PaintAction: URIRef
    Painting: URIRef
    PalliativeProcedure: URIRef
    Paperback: URIRef
    ParcelDelivery: URIRef
    ParcelService: URIRef
    ParentAudience: URIRef
    ParentalSupport: URIRef
    Park: URIRef
    ParkingFacility: URIRef
    ParkingMap: URIRef
    PartiallyInForce: URIRef
    Pathology: URIRef
    PathologyTest: URIRef
    Patient: URIRef
    PatientExperienceHealthAspect: URIRef
    PawnShop: URIRef
    PayAction: URIRef
    PaymentAutomaticallyApplied: URIRef
    PaymentCard: URIRef
    PaymentChargeSpecification: URIRef
    PaymentComplete: URIRef
    PaymentDeclined: URIRef
    PaymentDue: URIRef
    PaymentMethod: URIRef
    PaymentPastDue: URIRef
    PaymentService: URIRef
    PaymentStatusType: URIRef
    Pediatric: URIRef
    PeopleAudience: URIRef
    PercutaneousProcedure: URIRef
    PerformAction: URIRef
    PerformanceRole: URIRef
    PerformingArtsTheater: URIRef
    PerformingGroup: URIRef
    Periodical: URIRef
    Permit: URIRef
    Person: URIRef
    PetStore: URIRef
    Pharmacy: URIRef
    PharmacySpecialty: URIRef
    Photograph: URIRef
    PhotographAction: URIRef
    PhysicalActivity: URIRef
    PhysicalActivityCategory: URIRef
    PhysicalExam: URIRef
    PhysicalTherapy: URIRef
    Physician: URIRef
    Physiotherapy: URIRef
    Place: URIRef
    PlaceOfWorship: URIRef
    PlaceboControlledTrial: URIRef
    PlanAction: URIRef
    PlasticSurgery: URIRef
    Play: URIRef
    PlayAction: URIRef
    Playground: URIRef
    Plumber: URIRef
    PodcastEpisode: URIRef
    PodcastSeason: URIRef
    PodcastSeries: URIRef
    Podiatric: URIRef
    PoliceStation: URIRef
    Pond: URIRef
    PostOffice: URIRef
    PostalAddress: URIRef
    PostalCodeRangeSpecification: URIRef
    Poster: URIRef
    PotentialActionStatus: URIRef
    PreOrder: URIRef
    PreOrderAction: URIRef
    PreSale: URIRef
    PregnancyHealthAspect: URIRef
    PrependAction: URIRef
    Preschool: URIRef
    PrescriptionOnly: URIRef
    PresentationDigitalDocument: URIRef
    PreventionHealthAspect: URIRef
    PreventionIndication: URIRef
    PriceComponentTypeEnumeration: URIRef
    PriceSpecification: URIRef
    PriceTypeEnumeration: URIRef
    PrimaryCare: URIRef
    Prion: URIRef
    Product: URIRef
    ProductCollection: URIRef
    ProductGroup: URIRef
    ProductModel: URIRef
    ProfessionalService: URIRef
    ProfilePage: URIRef
    PrognosisHealthAspect: URIRef
    ProgramMembership: URIRef
    Project: URIRef
    PronounceableText: URIRef
    Property: URIRef
    PropertyValue: URIRef
    PropertyValueSpecification: URIRef
    Protein: URIRef
    Protozoa: URIRef
    Psychiatric: URIRef
    PsychologicalTreatment: URIRef
    PublicHealth: URIRef
    PublicHolidays: URIRef
    PublicSwimmingPool: URIRef
    PublicToilet: URIRef
    PublicationEvent: URIRef
    PublicationIssue: URIRef
    PublicationVolume: URIRef
    Pulmonary: URIRef
    QAPage: URIRef
    QualitativeValue: URIRef
    QuantitativeValue: URIRef
    QuantitativeValueDistribution: URIRef
    Quantity: URIRef
    Question: URIRef
    Quiz: URIRef
    Quotation: URIRef
    QuoteAction: URIRef
    RVPark: URIRef
    RadiationTherapy: URIRef
    RadioBroadcastService: URIRef
    RadioChannel: URIRef
    RadioClip: URIRef
    RadioEpisode: URIRef
    RadioSeason: URIRef
    RadioSeries: URIRef
    RadioStation: URIRef
    Radiography: URIRef
    RandomizedTrial: URIRef
    Rating: URIRef
    ReactAction: URIRef
    ReadAction: URIRef
    ReadPermission: URIRef
    RealEstateAgent: URIRef
    RealEstateListing: URIRef
    RearWheelDriveConfiguration: URIRef
    ReceiveAction: URIRef
    Recipe: URIRef
    Recommendation: URIRef
    RecommendedDoseSchedule: URIRef
    Recruiting: URIRef
    RecyclingCenter: URIRef
    RefundTypeEnumeration: URIRef
    RefurbishedCondition: URIRef
    RegisterAction: URIRef
    Registry: URIRef
    ReimbursementCap: URIRef
    RejectAction: URIRef
    RelatedTopicsHealthAspect: URIRef
    RemixAlbum: URIRef
    Renal: URIRef
    RentAction: URIRef
    RentalCarReservation: URIRef
    RentalVehicleUsage: URIRef
    RepaymentSpecification: URIRef
    ReplaceAction: URIRef
    ReplyAction: URIRef
    Report: URIRef
    ReportageNewsArticle: URIRef
    ReportedDoseSchedule: URIRef
    ResearchOrganization: URIRef
    ResearchProject: URIRef
    Researcher: URIRef
    Reservation: URIRef
    ReservationCancelled: URIRef
    ReservationConfirmed: URIRef
    ReservationHold: URIRef
    ReservationPackage: URIRef
    ReservationPending: URIRef
    ReservationStatusType: URIRef
    ReserveAction: URIRef
    Reservoir: URIRef
    Residence: URIRef
    Resort: URIRef
    RespiratoryTherapy: URIRef
    Restaurant: URIRef
    RestockingFees: URIRef
    RestrictedDiet: URIRef
    ResultsAvailable: URIRef
    ResultsNotAvailable: URIRef
    ResumeAction: URIRef
    Retail: URIRef
    ReturnAction: URIRef
    ReturnAtKiosk: URIRef
    ReturnByMail: URIRef
    ReturnFeesCustomerResponsibility: URIRef
    ReturnFeesEnumeration: URIRef
    ReturnInStore: URIRef
    ReturnLabelCustomerResponsibility: URIRef
    ReturnLabelDownloadAndPrint: URIRef
    ReturnLabelInBox: URIRef
    ReturnLabelSourceEnumeration: URIRef
    ReturnMethodEnumeration: URIRef
    ReturnShippingFees: URIRef
    Review: URIRef
    ReviewAction: URIRef
    ReviewNewsArticle: URIRef
    Rheumatologic: URIRef
    RightHandDriving: URIRef
    RisksOrComplicationsHealthAspect: URIRef
    RiverBodyOfWater: URIRef
    Role: URIRef
    RoofingContractor: URIRef
    Room: URIRef
    RsvpAction: URIRef
    RsvpResponseMaybe: URIRef
    RsvpResponseNo: URIRef
    RsvpResponseType: URIRef
    RsvpResponseYes: URIRef
    SRP: URIRef
    SafetyHealthAspect: URIRef
    SaleEvent: URIRef
    SalePrice: URIRef
    SatireOrParodyContent: URIRef
    SatiricalArticle: URIRef
    Saturday: URIRef
    Schedule: URIRef
    ScheduleAction: URIRef
    ScholarlyArticle: URIRef
    School: URIRef
    SchoolDistrict: URIRef
    ScreeningEvent: URIRef
    ScreeningHealthAspect: URIRef
    Sculpture: URIRef
    SeaBodyOfWater: URIRef
    SearchAction: URIRef
    SearchResultsPage: URIRef
    Season: URIRef
    Seat: URIRef
    SeatingMap: URIRef
    SeeDoctorHealthAspect: URIRef
    SeekToAction: URIRef
    SelfCareHealthAspect: URIRef
    SelfStorage: URIRef
    SellAction: URIRef
    SendAction: URIRef
    Series: URIRef
    Service: URIRef
    ServiceChannel: URIRef
    ShareAction: URIRef
    SheetMusic: URIRef
    ShippingDeliveryTime: URIRef
    ShippingRateSettings: URIRef
    ShoeStore: URIRef
    ShoppingCenter: URIRef
    ShortStory: URIRef
    SideEffectsHealthAspect: URIRef
    SingleBlindedTrial: URIRef
    SingleCenterTrial: URIRef
    SingleFamilyResidence: URIRef
    SinglePlayer: URIRef
    SingleRelease: URIRef
    SiteNavigationElement: URIRef
    SizeGroupEnumeration: URIRef
    SizeSpecification: URIRef
    SizeSystemEnumeration: URIRef
    SizeSystemImperial: URIRef
    SizeSystemMetric: URIRef
    SkiResort: URIRef
    Skin: URIRef
    SocialEvent: URIRef
    SocialMediaPosting: URIRef
    SoftwareApplication: URIRef
    SoftwareSourceCode: URIRef
    SoldOut: URIRef
    SolveMathAction: URIRef
    SomeProducts: URIRef
    SoundtrackAlbum: URIRef
    SpeakableSpecification: URIRef
    SpecialAnnouncement: URIRef
    Specialty: URIRef
    SpeechPathology: URIRef
    SpokenWordAlbum: URIRef
    SportingGoodsStore: URIRef
    SportsActivityLocation: URIRef
    SportsClub: URIRef
    SportsEvent: URIRef
    SportsOrganization: URIRef
    SportsTeam: URIRef
    SpreadsheetDigitalDocument: URIRef
    StadiumOrArena: URIRef
    StagedContent: URIRef
    StagesHealthAspect: URIRef
    State: URIRef
    Statement: URIRef
    StatisticalPopulation: URIRef
    StatusEnumeration: URIRef
    SteeringPositionValue: URIRef
    Store: URIRef
    StoreCreditRefund: URIRef
    StrengthTraining: URIRef
    StructuredValue: URIRef
    StudioAlbum: URIRef
    SubscribeAction: URIRef
    Subscription: URIRef
    Substance: URIRef
    SubwayStation: URIRef
    Suite: URIRef
    Sunday: URIRef
    SuperficialAnatomy: URIRef
    Surgical: URIRef
    SurgicalProcedure: URIRef
    SuspendAction: URIRef
    Suspended: URIRef
    SymptomsHealthAspect: URIRef
    Synagogue: URIRef
    TVClip: URIRef
    TVEpisode: URIRef
    TVSeason: URIRef
    TVSeries: URIRef
    Table: URIRef
    TakeAction: URIRef
    TattooParlor: URIRef
    Taxi: URIRef
    TaxiReservation: URIRef
    TaxiService: URIRef
    TaxiStand: URIRef
    TaxiVehicleUsage: URIRef
    Taxon: URIRef
    TechArticle: URIRef
    TelevisionChannel: URIRef
    TelevisionStation: URIRef
    TennisComplex: URIRef
    Terminated: URIRef
    Text: URIRef
    TextDigitalDocument: URIRef
    TheaterEvent: URIRef
    TheaterGroup: URIRef
    Therapeutic: URIRef
    TherapeuticProcedure: URIRef
    Thesis: URIRef
    Thing: URIRef
    Throat: URIRef
    Thursday: URIRef
    Ticket: URIRef
    TieAction: URIRef
    Time: URIRef
    TipAction: URIRef
    TireShop: URIRef
    TollFree: URIRef
    TouristAttraction: URIRef
    TouristDestination: URIRef
    TouristInformationCenter: URIRef
    TouristTrip: URIRef
    Toxicologic: URIRef
    ToyStore: URIRef
    TrackAction: URIRef
    TradeAction: URIRef
    TraditionalChinese: URIRef
    TrainReservation: URIRef
    TrainStation: URIRef
    TrainTrip: URIRef
    TransferAction: URIRef
    TransformedContent: URIRef
    TransitMap: URIRef
    TravelAction: URIRef
    TravelAgency: URIRef
    TreatmentIndication: URIRef
    TreatmentsHealthAspect: URIRef
    Trip: URIRef
    TripleBlindedTrial: URIRef
    Tuesday: URIRef
    TypeAndQuantityNode: URIRef
    TypesHealthAspect: URIRef
    UKNonprofitType: URIRef
    UKTrust: URIRef
    URL: URIRef
    USNonprofitType: URIRef
    Ultrasound: URIRef
    UnRegisterAction: URIRef
    UnemploymentSupport: URIRef
    UnincorporatedAssociationCharity: URIRef
    UnitPriceSpecification: URIRef
    UnofficialLegalValue: URIRef
    UpdateAction: URIRef
    Urologic: URIRef
    UsageOrScheduleHealthAspect: URIRef
    UseAction: URIRef
    UsedCondition: URIRef
    UserBlocks: URIRef
    UserCheckins: URIRef
    UserComments: URIRef
    UserDownloads: URIRef
    UserInteraction: URIRef
    UserLikes: URIRef
    UserPageVisits: URIRef
    UserPlays: URIRef
    UserPlusOnes: URIRef
    UserReview: URIRef
    UserTweets: URIRef
    VeganDiet: URIRef
    VegetarianDiet: URIRef
    Vehicle: URIRef
    Vein: URIRef
    VenueMap: URIRef
    Vessel: URIRef
    VeterinaryCare: URIRef
    VideoGallery: URIRef
    VideoGame: URIRef
    VideoGameClip: URIRef
    VideoGameSeries: URIRef
    VideoObject: URIRef
    VideoObjectSnapshot: URIRef
    ViewAction: URIRef
    VinylFormat: URIRef
    VirtualLocation: URIRef
    Virus: URIRef
    VisualArtsEvent: URIRef
    VisualArtwork: URIRef
    VitalSign: URIRef
    Volcano: URIRef
    VoteAction: URIRef
    WPAdBlock: URIRef
    WPFooter: URIRef
    WPHeader: URIRef
    WPSideBar: URIRef
    WantAction: URIRef
    WarrantyPromise: URIRef
    WarrantyScope: URIRef
    WatchAction: URIRef
    Waterfall: URIRef
    WearAction: URIRef
    WearableMeasurementBack: URIRef
    WearableMeasurementChestOrBust: URIRef
    WearableMeasurementCollar: URIRef
    WearableMeasurementCup: URIRef
    WearableMeasurementHeight: URIRef
    WearableMeasurementHips: URIRef
    WearableMeasurementInseam: URIRef
    WearableMeasurementLength: URIRef
    WearableMeasurementOutsideLeg: URIRef
    WearableMeasurementSleeve: URIRef
    WearableMeasurementTypeEnumeration: URIRef
    WearableMeasurementWaist: URIRef
    WearableMeasurementWidth: URIRef
    WearableSizeGroupBig: URIRef
    WearableSizeGroupBoys: URIRef
    WearableSizeGroupEnumeration: URIRef
    WearableSizeGroupExtraShort: URIRef
    WearableSizeGroupExtraTall: URIRef
    WearableSizeGroupGirls: URIRef
    WearableSizeGroupHusky: URIRef
    WearableSizeGroupInfants: URIRef
    WearableSizeGroupJuniors: URIRef
    WearableSizeGroupMaternity: URIRef
    WearableSizeGroupMens: URIRef
    WearableSizeGroupMisses: URIRef
    WearableSizeGroupPetite: URIRef
    WearableSizeGroupPlus: URIRef
    WearableSizeGroupRegular: URIRef
    WearableSizeGroupShort: URIRef
    WearableSizeGroupTall: URIRef
    WearableSizeGroupWomens: URIRef
    WearableSizeSystemAU: URIRef
    WearableSizeSystemBR: URIRef
    WearableSizeSystemCN: URIRef
    WearableSizeSystemContinental: URIRef
    WearableSizeSystemDE: URIRef
    WearableSizeSystemEN13402: URIRef
    WearableSizeSystemEnumeration: URIRef
    WearableSizeSystemEurope: URIRef
    WearableSizeSystemFR: URIRef
    WearableSizeSystemGS1: URIRef
    WearableSizeSystemIT: URIRef
    WearableSizeSystemJP: URIRef
    WearableSizeSystemMX: URIRef
    WearableSizeSystemUK: URIRef
    WearableSizeSystemUS: URIRef
    WebAPI: URIRef
    WebApplication: URIRef
    WebContent: URIRef
    WebPage: URIRef
    WebPageElement: URIRef
    WebSite: URIRef
    Wednesday: URIRef
    WesternConventional: URIRef
    Wholesale: URIRef
    WholesaleStore: URIRef
    WinAction: URIRef
    Winery: URIRef
    Withdrawn: URIRef
    WorkBasedProgram: URIRef
    WorkersUnion: URIRef
    WriteAction: URIRef
    WritePermission: URIRef
    XPathType: URIRef
    XRay: URIRef
    ZoneBoardingPolicy: URIRef
    Zoo: URIRef
    about: URIRef
    abridged: URIRef
    abstract: URIRef
    accelerationTime: URIRef
    acceptedAnswer: URIRef
    acceptedOffer: URIRef
    acceptedPaymentMethod: URIRef
    acceptsReservations: URIRef
    accessCode: URIRef
    accessMode: URIRef
    accessModeSufficient: URIRef
    accessibilityAPI: URIRef
    accessibilityControl: URIRef
    accessibilityFeature: URIRef
    accessibilityHazard: URIRef
    accessibilitySummary: URIRef
    accommodationCategory: URIRef
    accommodationFloorPlan: URIRef
    accountId: URIRef
    accountMinimumInflow: URIRef
    accountOverdraftLimit: URIRef
    accountablePerson: URIRef
    acquireLicensePage: URIRef
    acquiredFrom: URIRef
    acrissCode: URIRef
    actionAccessibilityRequirement: URIRef
    actionApplication: URIRef
    actionOption: URIRef
    actionPlatform: URIRef
    actionStatus: URIRef
    actionableFeedbackPolicy: URIRef
    activeIngredient: URIRef
    activityDuration: URIRef
    activityFrequency: URIRef
    actor: URIRef
    actors: URIRef
    addOn: URIRef
    additionalName: URIRef
    additionalNumberOfGuests: URIRef
    additionalProperty: URIRef
    additionalType: URIRef
    additionalVariable: URIRef
    address: URIRef
    addressCountry: URIRef
    addressLocality: URIRef
    addressRegion: URIRef
    administrationRoute: URIRef
    advanceBookingRequirement: URIRef
    adverseOutcome: URIRef
    affectedBy: URIRef
    affiliation: URIRef
    afterMedia: URIRef
    agent: URIRef
    aggregateRating: URIRef
    aircraft: URIRef
    album: URIRef
    albumProductionType: URIRef
    albumRelease: URIRef
    albumReleaseType: URIRef
    albums: URIRef
    alcoholWarning: URIRef
    algorithm: URIRef
    alignmentType: URIRef
    alternateName: URIRef
    alternativeHeadline: URIRef
    alternativeOf: URIRef
    alumni: URIRef
    alumniOf: URIRef
    amenityFeature: URIRef
    amount: URIRef
    amountOfThisGood: URIRef
    announcementLocation: URIRef
    annualPercentageRate: URIRef
    answerCount: URIRef
    answerExplanation: URIRef
    antagonist: URIRef
    appearance: URIRef
    applicableLocation: URIRef
    applicantLocationRequirements: URIRef
    application: URIRef
    applicationCategory: URIRef
    applicationContact: URIRef
    applicationDeadline: URIRef
    applicationStartDate: URIRef
    applicationSubCategory: URIRef
    applicationSuite: URIRef
    appliesToDeliveryMethod: URIRef
    appliesToPaymentMethod: URIRef
    archiveHeld: URIRef
    archivedAt: URIRef
    area: URIRef
    areaServed: URIRef
    arrivalAirport: URIRef
    arrivalBoatTerminal: URIRef
    arrivalBusStop: URIRef
    arrivalGate: URIRef
    arrivalPlatform: URIRef
    arrivalStation: URIRef
    arrivalTerminal: URIRef
    arrivalTime: URIRef
    artEdition: URIRef
    artMedium: URIRef
    arterialBranch: URIRef
    artform: URIRef
    articleBody: URIRef
    articleSection: URIRef
    artist: URIRef
    artworkSurface: URIRef
    aspect: URIRef
    assembly: URIRef
    assemblyVersion: URIRef
    assesses: URIRef
    associatedAnatomy: URIRef
    associatedArticle: URIRef
    associatedClaimReview: URIRef
    associatedDisease: URIRef
    associatedMedia: URIRef
    associatedMediaReview: URIRef
    associatedPathophysiology: URIRef
    associatedReview: URIRef
    athlete: URIRef
    attendee: URIRef
    attendees: URIRef
    audience: URIRef
    audienceType: URIRef
    audio: URIRef
    authenticator: URIRef
    author: URIRef
    availability: URIRef
    availabilityEnds: URIRef
    availabilityStarts: URIRef
    availableAtOrFrom: URIRef
    availableChannel: URIRef
    availableDeliveryMethod: URIRef
    availableFrom: URIRef
    availableIn: URIRef
    availableLanguage: URIRef
    availableOnDevice: URIRef
    availableService: URIRef
    availableStrength: URIRef
    availableTest: URIRef
    availableThrough: URIRef
    award: URIRef
    awards: URIRef
    awayTeam: URIRef
    backstory: URIRef
    bankAccountType: URIRef
    baseSalary: URIRef
    bccRecipient: URIRef
    bed: URIRef
    beforeMedia: URIRef
    beneficiaryBank: URIRef
    benefits: URIRef
    benefitsSummaryUrl: URIRef
    bestRating: URIRef
    billingAddress: URIRef
    billingDuration: URIRef
    billingIncrement: URIRef
    billingPeriod: URIRef
    billingStart: URIRef
    bioChemInteraction: URIRef
    bioChemSimilarity: URIRef
    biologicalRole: URIRef
    biomechnicalClass: URIRef
    birthDate: URIRef
    birthPlace: URIRef
    bitrate: URIRef
    blogPost: URIRef
    blogPosts: URIRef
    bloodSupply: URIRef
    boardingGroup: URIRef
    boardingPolicy: URIRef
    bodyLocation: URIRef
    bodyType: URIRef
    bookEdition: URIRef
    bookFormat: URIRef
    bookingAgent: URIRef
    bookingTime: URIRef
    borrower: URIRef
    box: URIRef
    branch: URIRef
    branchCode: URIRef
    branchOf: URIRef
    brand: URIRef
    breadcrumb: URIRef
    breastfeedingWarning: URIRef
    broadcastAffiliateOf: URIRef
    broadcastChannelId: URIRef
    broadcastDisplayName: URIRef
    broadcastFrequency: URIRef
    broadcastFrequencyValue: URIRef
    broadcastOfEvent: URIRef
    broadcastServiceTier: URIRef
    broadcastSignalModulation: URIRef
    broadcastSubChannel: URIRef
    broadcastTimezone: URIRef
    broadcaster: URIRef
    broker: URIRef
    browserRequirements: URIRef
    busName: URIRef
    busNumber: URIRef
    businessDays: URIRef
    businessFunction: URIRef
    buyer: URIRef
    byArtist: URIRef
    byDay: URIRef
    byMonth: URIRef
    byMonthDay: URIRef
    byMonthWeek: URIRef
    callSign: URIRef
    calories: URIRef
    candidate: URIRef
    caption: URIRef
    carbohydrateContent: URIRef
    cargoVolume: URIRef
    carrier: URIRef
    carrierRequirements: URIRef
    cashBack: URIRef
    catalog: URIRef
    catalogNumber: URIRef
    category: URIRef
    causeOf: URIRef
    ccRecipient: URIRef
    character: URIRef
    characterAttribute: URIRef
    characterName: URIRef
    cheatCode: URIRef
    checkinTime: URIRef
    checkoutTime: URIRef
    chemicalComposition: URIRef
    chemicalRole: URIRef
    childMaxAge: URIRef
    childMinAge: URIRef
    childTaxon: URIRef
    children: URIRef
    cholesterolContent: URIRef
    circle: URIRef
    citation: URIRef
    claimInterpreter: URIRef
    claimReviewed: URIRef
    clincalPharmacology: URIRef
    clinicalPharmacology: URIRef
    clipNumber: URIRef
    closes: URIRef
    coach: URIRef
    code: URIRef
    codeRepository: URIRef
    codeSampleType: URIRef
    codeValue: URIRef
    codingSystem: URIRef
    colleague: URIRef
    colleagues: URIRef
    collection: URIRef
    collectionSize: URIRef
    color: URIRef
    colorist: URIRef
    comment: URIRef
    commentCount: URIRef
    commentText: URIRef
    commentTime: URIRef
    competencyRequired: URIRef
    competitor: URIRef
    composer: URIRef
    comprisedOf: URIRef
    conditionsOfAccess: URIRef
    confirmationNumber: URIRef
    connectedTo: URIRef
    constrainingProperty: URIRef
    contactOption: URIRef
    contactPoint: URIRef
    contactPoints: URIRef
    contactType: URIRef
    contactlessPayment: URIRef
    containedIn: URIRef
    containedInPlace: URIRef
    containsPlace: URIRef
    containsSeason: URIRef
    contentLocation: URIRef
    contentRating: URIRef
    contentReferenceTime: URIRef
    contentSize: URIRef
    contentType: URIRef
    contentUrl: URIRef
    contraindication: URIRef
    contributor: URIRef
    cookTime: URIRef
    cookingMethod: URIRef
    copyrightHolder: URIRef
    copyrightNotice: URIRef
    copyrightYear: URIRef
    correction: URIRef
    correctionsPolicy: URIRef
    costCategory: URIRef
    costCurrency: URIRef
    costOrigin: URIRef
    costPerUnit: URIRef
    countriesNotSupported: URIRef
    countriesSupported: URIRef
    countryOfAssembly: URIRef
    countryOfLastProcessing: URIRef
    countryOfOrigin: URIRef
    course: URIRef
    courseCode: URIRef
    courseMode: URIRef
    coursePrerequisites: URIRef
    courseWorkload: URIRef
    coverageEndTime: URIRef
    coverageStartTime: URIRef
    creativeWorkStatus: URIRef
    creator: URIRef
    credentialCategory: URIRef
    creditText: URIRef
    creditedTo: URIRef
    cssSelector: URIRef
    currenciesAccepted: URIRef
    currency: URIRef
    currentExchangeRate: URIRef
    customer: URIRef
    customerRemorseReturnFees: URIRef
    customerRemorseReturnLabelSource: URIRef
    customerRemorseReturnShippingFeesAmount: URIRef
    cutoffTime: URIRef
    cvdCollectionDate: URIRef
    cvdFacilityCounty: URIRef
    cvdFacilityId: URIRef
    cvdNumBeds: URIRef
    cvdNumBedsOcc: URIRef
    cvdNumC19Died: URIRef
    cvdNumC19HOPats: URIRef
    cvdNumC19HospPats: URIRef
    cvdNumC19MechVentPats: URIRef
    cvdNumC19OFMechVentPats: URIRef
    cvdNumC19OverflowPats: URIRef
    cvdNumICUBeds: URIRef
    cvdNumICUBedsOcc: URIRef
    cvdNumTotBeds: URIRef
    cvdNumVent: URIRef
    cvdNumVentUse: URIRef
    dataFeedElement: URIRef
    dataset: URIRef
    datasetTimeInterval: URIRef
    dateCreated: URIRef
    dateDeleted: URIRef
    dateIssued: URIRef
    dateModified: URIRef
    datePosted: URIRef
    datePublished: URIRef
    dateRead: URIRef
    dateReceived: URIRef
    dateSent: URIRef
    dateVehicleFirstRegistered: URIRef
    dateline: URIRef
    dayOfWeek: URIRef
    deathDate: URIRef
    deathPlace: URIRef
    defaultValue: URIRef
    deliveryAddress: URIRef
    deliveryLeadTime: URIRef
    deliveryMethod: URIRef
    deliveryStatus: URIRef
    deliveryTime: URIRef
    department: URIRef
    departureAirport: URIRef
    departureBoatTerminal: URIRef
    departureBusStop: URIRef
    departureGate: URIRef
    departurePlatform: URIRef
    departureStation: URIRef
    departureTerminal: URIRef
    departureTime: URIRef
    dependencies: URIRef
    depth: URIRef
    description: URIRef
    device: URIRef
    diagnosis: URIRef
    diagram: URIRef
    diet: URIRef
    dietFeatures: URIRef
    differentialDiagnosis: URIRef
    directApply: URIRef
    director: URIRef
    directors: URIRef
    disambiguatingDescription: URIRef
    discount: URIRef
    discountCode: URIRef
    discountCurrency: URIRef
    discusses: URIRef
    discussionUrl: URIRef
    diseasePreventionInfo: URIRef
    diseaseSpreadStatistics: URIRef
    dissolutionDate: URIRef
    distance: URIRef
    distinguishingSign: URIRef
    distribution: URIRef
    diversityPolicy: URIRef
    diversityStaffingReport: URIRef
    documentation: URIRef
    doesNotShip: URIRef
    domainIncludes: URIRef
    domiciledMortgage: URIRef
    doorTime: URIRef
    dosageForm: URIRef
    doseSchedule: URIRef
    doseUnit: URIRef
    doseValue: URIRef
    downPayment: URIRef
    downloadUrl: URIRef
    downvoteCount: URIRef
    drainsTo: URIRef
    driveWheelConfiguration: URIRef
    dropoffLocation: URIRef
    dropoffTime: URIRef
    drug: URIRef
    drugClass: URIRef
    drugUnit: URIRef
    duns: URIRef
    duplicateTherapy: URIRef
    duration: URIRef
    durationOfWarranty: URIRef
    duringMedia: URIRef
    earlyPrepaymentPenalty: URIRef
    editEIDR: URIRef
    editor: URIRef
    eduQuestionType: URIRef
    educationRequirements: URIRef
    educationalAlignment: URIRef
    educationalCredentialAwarded: URIRef
    educationalFramework: URIRef
    educationalLevel: URIRef
    educationalProgramMode: URIRef
    educationalRole: URIRef
    educationalUse: URIRef
    elevation: URIRef
    eligibilityToWorkRequirement: URIRef
    eligibleCustomerType: URIRef
    eligibleDuration: URIRef
    eligibleQuantity: URIRef
    eligibleRegion: URIRef
    eligibleTransactionVolume: URIRef
    email: URIRef
    embedUrl: URIRef
    embeddedTextCaption: URIRef
    emissionsCO2: URIRef
    employee: URIRef
    employees: URIRef
    employerOverview: URIRef
    employmentType: URIRef
    employmentUnit: URIRef
    encodesBioChemEntity: URIRef
    encodesCreativeWork: URIRef
    encoding: URIRef
    encodingFormat: URIRef
    encodingType: URIRef
    encodings: URIRef
    endDate: URIRef
    endOffset: URIRef
    endTime: URIRef
    endorsee: URIRef
    endorsers: URIRef
    energyEfficiencyScaleMax: URIRef
    energyEfficiencyScaleMin: URIRef
    engineDisplacement: URIRef
    enginePower: URIRef
    engineType: URIRef
    entertainmentBusiness: URIRef
    epidemiology: URIRef
    episode: URIRef
    episodeNumber: URIRef
    episodes: URIRef
    equal: URIRef
    error: URIRef
    estimatedCost: URIRef
    estimatedFlightDuration: URIRef
    estimatedSalary: URIRef
    estimatesRiskOf: URIRef
    ethicsPolicy: URIRef
    event: URIRef
    eventAttendanceMode: URIRef
    eventSchedule: URIRef
    eventStatus: URIRef
    events: URIRef
    evidenceLevel: URIRef
    evidenceOrigin: URIRef
    exampleOfWork: URIRef
    exceptDate: URIRef
    exchangeRateSpread: URIRef
    executableLibraryName: URIRef
    exerciseCourse: URIRef
    exercisePlan: URIRef
    exerciseRelatedDiet: URIRef
    exerciseType: URIRef
    exifData: URIRef
    expectedArrivalFrom: URIRef
    expectedArrivalUntil: URIRef
    expectedPrognosis: URIRef
    expectsAcceptanceOf: URIRef
    experienceInPlaceOfEducation: URIRef
    experienceRequirements: URIRef
    expertConsiderations: URIRef
    expires: URIRef
    expressedIn: URIRef
    familyName: URIRef
    fatContent: URIRef
    faxNumber: URIRef
    featureList: URIRef
    feesAndCommissionsSpecification: URIRef
    fiberContent: URIRef
    fileFormat: URIRef
    fileSize: URIRef
    financialAidEligible: URIRef
    firstAppearance: URIRef
    firstPerformance: URIRef
    flightDistance: URIRef
    flightNumber: URIRef
    floorLevel: URIRef
    floorLimit: URIRef
    floorSize: URIRef
    followee: URIRef
    follows: URIRef
    followup: URIRef
    foodEstablishment: URIRef
    foodEvent: URIRef
    foodWarning: URIRef
    founder: URIRef
    founders: URIRef
    foundingDate: URIRef
    foundingLocation: URIRef
    free: URIRef
    freeShippingThreshold: URIRef
    frequency: URIRef
    fromLocation: URIRef
    fuelCapacity: URIRef
    fuelConsumption: URIRef
    fuelEfficiency: URIRef
    fuelType: URIRef
    functionalClass: URIRef
    fundedItem: URIRef
    funder: URIRef
    game: URIRef
    gameItem: URIRef
    gameLocation: URIRef
    gamePlatform: URIRef
    gameServer: URIRef
    gameTip: URIRef
    gender: URIRef
    genre: URIRef
    geo: URIRef
    geoContains: URIRef
    geoCoveredBy: URIRef
    geoCovers: URIRef
    geoCrosses: URIRef
    geoDisjoint: URIRef
    geoEquals: URIRef
    geoIntersects: URIRef
    geoMidpoint: URIRef
    geoOverlaps: URIRef
    geoRadius: URIRef
    geoTouches: URIRef
    geoWithin: URIRef
    geographicArea: URIRef
    gettingTestedInfo: URIRef
    givenName: URIRef
    globalLocationNumber: URIRef
    governmentBenefitsInfo: URIRef
    gracePeriod: URIRef
    grantee: URIRef
    greater: URIRef
    greaterOrEqual: URIRef
    gtin: URIRef
    gtin12: URIRef
    gtin13: URIRef
    gtin14: URIRef
    gtin8: URIRef
    guideline: URIRef
    guidelineDate: URIRef
    guidelineSubject: URIRef
    handlingTime: URIRef
    hasBioChemEntityPart: URIRef
    hasBioPolymerSequence: URIRef
    hasBroadcastChannel: URIRef
    hasCategoryCode: URIRef
    hasCourse: URIRef
    hasCourseInstance: URIRef
    hasCredential: URIRef
    hasDefinedTerm: URIRef
    hasDeliveryMethod: URIRef
    hasDigitalDocumentPermission: URIRef
    hasDriveThroughService: URIRef
    hasEnergyConsumptionDetails: URIRef
    hasEnergyEfficiencyCategory: URIRef
    hasHealthAspect: URIRef
    hasMap: URIRef
    hasMeasurement: URIRef
    hasMenu: URIRef
    hasMenuItem: URIRef
    hasMenuSection: URIRef
    hasMerchantReturnPolicy: URIRef
    hasMolecularFunction: URIRef
    hasOccupation: URIRef
    hasOfferCatalog: URIRef
    hasPOS: URIRef
    hasPart: URIRef
    hasRepresentation: URIRef
    hasVariant: URIRef
    headline: URIRef
    healthCondition: URIRef
    healthPlanCoinsuranceOption: URIRef
    healthPlanCoinsuranceRate: URIRef
    healthPlanCopay: URIRef
    healthPlanCopayOption: URIRef
    healthPlanCostSharing: URIRef
    healthPlanDrugOption: URIRef
    healthPlanDrugTier: URIRef
    healthPlanId: URIRef
    healthPlanMarketingUrl: URIRef
    healthPlanNetworkId: URIRef
    healthPlanNetworkTier: URIRef
    healthPlanPharmacyCategory: URIRef
    healthcareReportingData: URIRef
    height: URIRef
    highPrice: URIRef
    hiringOrganization: URIRef
    holdingArchive: URIRef
    homeLocation: URIRef
    homeTeam: URIRef
    honorificPrefix: URIRef
    honorificSuffix: URIRef
    hospitalAffiliation: URIRef
    hostingOrganization: URIRef
    hoursAvailable: URIRef
    howPerformed: URIRef
    httpMethod: URIRef
    iataCode: URIRef
    icaoCode: URIRef
    identifier: URIRef
    identifyingExam: URIRef
    identifyingTest: URIRef
    illustrator: URIRef
    image: URIRef
    imagingTechnique: URIRef
    inAlbum: URIRef
    inBroadcastLineup: URIRef
    inChI: URIRef
    inChIKey: URIRef
    inCodeSet: URIRef
    inDefinedTermSet: URIRef
    inLanguage: URIRef
    inPlaylist: URIRef
    inProductGroupWithID: URIRef
    inStoreReturnsOffered: URIRef
    inSupportOf: URIRef
    incentiveCompensation: URIRef
    incentives: URIRef
    includedComposition: URIRef
    includedDataCatalog: URIRef
    includedInDataCatalog: URIRef
    includedInHealthInsurancePlan: URIRef
    includedRiskFactor: URIRef
    includesAttraction: URIRef
    includesHealthPlanFormulary: URIRef
    includesHealthPlanNetwork: URIRef
    includesObject: URIRef
    increasesRiskOf: URIRef
    industry: URIRef
    ineligibleRegion: URIRef
    infectiousAgent: URIRef
    infectiousAgentClass: URIRef
    ingredients: URIRef
    inker: URIRef
    insertion: URIRef
    installUrl: URIRef
    instructor: URIRef
    instrument: URIRef
    intensity: URIRef
    interactingDrug: URIRef
    interactionCount: URIRef
    interactionService: URIRef
    interactionStatistic: URIRef
    interactionType: URIRef
    interactivityType: URIRef
    interestRate: URIRef
    interpretedAsClaim: URIRef
    inventoryLevel: URIRef
    inverseOf: URIRef
    isAcceptingNewPatients: URIRef
    isAccessibleForFree: URIRef
    isAccessoryOrSparePartFor: URIRef
    isAvailableGenerically: URIRef
    isBasedOn: URIRef
    isBasedOnUrl: URIRef
    isConsumableFor: URIRef
    isEncodedByBioChemEntity: URIRef
    isFamilyFriendly: URIRef
    isGift: URIRef
    isInvolvedInBiologicalProcess: URIRef
    isLiveBroadcast: URIRef
    isLocatedInSubcellularLocation: URIRef
    isPartOf: URIRef
    isPartOfBioChemEntity: URIRef
    isPlanForApartment: URIRef
    isProprietary: URIRef
    isRelatedTo: URIRef
    isResizable: URIRef
    isSimilarTo: URIRef
    isUnlabelledFallback: URIRef
    isVariantOf: URIRef
    isbn: URIRef
    isicV4: URIRef
    isrcCode: URIRef
    issn: URIRef
    issueNumber: URIRef
    issuedBy: URIRef
    issuedThrough: URIRef
    iswcCode: URIRef
    item: URIRef
    itemCondition: URIRef
    itemDefectReturnFees: URIRef
    itemDefectReturnLabelSource: URIRef
    itemDefectReturnShippingFeesAmount: URIRef
    itemListElement: URIRef
    itemListOrder: URIRef
    itemLocation: URIRef
    itemOffered: URIRef
    itemReviewed: URIRef
    itemShipped: URIRef
    itinerary: URIRef
    iupacName: URIRef
    jobBenefits: URIRef
    jobImmediateStart: URIRef
    jobLocation: URIRef
    jobLocationType: URIRef
    jobStartDate: URIRef
    jobTitle: URIRef
    jurisdiction: URIRef
    keywords: URIRef
    knownVehicleDamages: URIRef
    knows: URIRef
    knowsAbout: URIRef
    knowsLanguage: URIRef
    labelDetails: URIRef
    landlord: URIRef
    language: URIRef
    lastReviewed: URIRef
    latitude: URIRef
    layoutImage: URIRef
    learningResourceType: URIRef
    leaseLength: URIRef
    legalName: URIRef
    legalStatus: URIRef
    legislationApplies: URIRef
    legislationChanges: URIRef
    legislationConsolidates: URIRef
    legislationDate: URIRef
    legislationDateVersion: URIRef
    legislationIdentifier: URIRef
    legislationJurisdiction: URIRef
    legislationLegalForce: URIRef
    legislationLegalValue: URIRef
    legislationPassedBy: URIRef
    legislationResponsible: URIRef
    legislationTransposes: URIRef
    legislationType: URIRef
    leiCode: URIRef
    lender: URIRef
    lesser: URIRef
    lesserOrEqual: URIRef
    letterer: URIRef
    license: URIRef
    line: URIRef
    linkRelationship: URIRef
    liveBlogUpdate: URIRef
    loanMortgageMandateAmount: URIRef
    loanPaymentAmount: URIRef
    loanPaymentFrequency: URIRef
    loanRepaymentForm: URIRef
    loanTerm: URIRef
    loanType: URIRef
    location: URIRef
    locationCreated: URIRef
    lodgingUnitDescription: URIRef
    lodgingUnitType: URIRef
    logo: URIRef
    longitude: URIRef
    loser: URIRef
    lowPrice: URIRef
    lyricist: URIRef
    lyrics: URIRef
    mainContentOfPage: URIRef
    mainEntity: URIRef
    mainEntityOfPage: URIRef
    maintainer: URIRef
    makesOffer: URIRef
    manufacturer: URIRef
    map: URIRef
    mapType: URIRef
    maps: URIRef
    marginOfError: URIRef
    masthead: URIRef
    material: URIRef
    materialExtent: URIRef
    mathExpression: URIRef
    maxPrice: URIRef
    maxValue: URIRef
    maximumAttendeeCapacity: URIRef
    maximumEnrollment: URIRef
    maximumIntake: URIRef
    maximumPhysicalAttendeeCapacity: URIRef
    maximumVirtualAttendeeCapacity: URIRef
    mealService: URIRef
    measuredProperty: URIRef
    measuredValue: URIRef
    measurementTechnique: URIRef
    mechanismOfAction: URIRef
    mediaAuthenticityCategory: URIRef
    mediaItemAppearance: URIRef
    median: URIRef
    medicalAudience: URIRef
    medicalSpecialty: URIRef
    medicineSystem: URIRef
    meetsEmissionStandard: URIRef
    member: URIRef
    memberOf: URIRef
    members: URIRef
    membershipNumber: URIRef
    membershipPointsEarned: URIRef
    memoryRequirements: URIRef
    mentions: URIRef
    menu: URIRef
    menuAddOn: URIRef
    merchant: URIRef
    merchantReturnDays: URIRef
    merchantReturnLink: URIRef
    messageAttachment: URIRef
    mileageFromOdometer: URIRef
    minPrice: URIRef
    minValue: URIRef
    minimumPaymentDue: URIRef
    missionCoveragePrioritiesPolicy: URIRef
    model: URIRef
    modelDate: URIRef
    modifiedTime: URIRef
    molecularFormula: URIRef
    molecularWeight: URIRef
    monoisotopicMolecularWeight: URIRef
    monthlyMinimumRepaymentAmount: URIRef
    monthsOfExperience: URIRef
    mpn: URIRef
    multipleValues: URIRef
    muscleAction: URIRef
    musicArrangement: URIRef
    musicBy: URIRef
    musicCompositionForm: URIRef
    musicGroupMember: URIRef
    musicReleaseFormat: URIRef
    musicalKey: URIRef
    naics: URIRef
    name: URIRef
    namedPosition: URIRef
    nationality: URIRef
    naturalProgression: URIRef
    negativeNotes: URIRef
    nerve: URIRef
    nerveMotor: URIRef
    netWorth: URIRef
    newsUpdatesAndGuidelines: URIRef
    nextItem: URIRef
    noBylinesPolicy: URIRef
    nonEqual: URIRef
    nonProprietaryName: URIRef
    nonprofitStatus: URIRef
    normalRange: URIRef
    nsn: URIRef
    numAdults: URIRef
    numChildren: URIRef
    numConstraints: URIRef
    numTracks: URIRef
    numberOfAccommodationUnits: URIRef
    numberOfAirbags: URIRef
    numberOfAvailableAccommodationUnits: URIRef
    numberOfAxles: URIRef
    numberOfBathroomsTotal: URIRef
    numberOfBedrooms: URIRef
    numberOfBeds: URIRef
    numberOfCredits: URIRef
    numberOfDoors: URIRef
    numberOfEmployees: URIRef
    numberOfEpisodes: URIRef
    numberOfForwardGears: URIRef
    numberOfFullBathrooms: URIRef
    numberOfItems: URIRef
    numberOfLoanPayments: URIRef
    numberOfPages: URIRef
    numberOfPartialBathrooms: URIRef
    numberOfPlayers: URIRef
    numberOfPreviousOwners: URIRef
    numberOfRooms: URIRef
    numberOfSeasons: URIRef
    numberedPosition: URIRef
    nutrition: URIRef
    object: URIRef
    observationDate: URIRef
    observedNode: URIRef
    occupancy: URIRef
    occupationLocation: URIRef
    occupationalCategory: URIRef
    occupationalCredentialAwarded: URIRef
    offerCount: URIRef
    offeredBy: URIRef
    offers: URIRef
    offersPrescriptionByMail: URIRef
    openingHours: URIRef
    openingHoursSpecification: URIRef
    opens: URIRef
    operatingSystem: URIRef
    opponent: URIRef
    option: URIRef
    orderDate: URIRef
    orderDelivery: URIRef
    orderItemNumber: URIRef
    orderItemStatus: URIRef
    orderNumber: URIRef
    orderQuantity: URIRef
    orderStatus: URIRef
    orderedItem: URIRef
    organizer: URIRef
    originAddress: URIRef
    originalMediaContextDescription: URIRef
    originalMediaLink: URIRef
    originatesFrom: URIRef
    overdosage: URIRef
    ownedFrom: URIRef
    ownedThrough: URIRef
    ownershipFundingInfo: URIRef
    owns: URIRef
    pageEnd: URIRef
    pageStart: URIRef
    pagination: URIRef
    parent: URIRef
    parentItem: URIRef
    parentOrganization: URIRef
    parentService: URIRef
    parentTaxon: URIRef
    parents: URIRef
    partOfEpisode: URIRef
    partOfInvoice: URIRef
    partOfOrder: URIRef
    partOfSeason: URIRef
    partOfSeries: URIRef
    partOfSystem: URIRef
    partOfTVSeries: URIRef
    partOfTrip: URIRef
    participant: URIRef
    partySize: URIRef
    passengerPriorityStatus: URIRef
    passengerSequenceNumber: URIRef
    pathophysiology: URIRef
    pattern: URIRef
    payload: URIRef
    paymentAccepted: URIRef
    paymentDue: URIRef
    paymentDueDate: URIRef
    paymentMethod: URIRef
    paymentMethodId: URIRef
    paymentStatus: URIRef
    paymentUrl: URIRef
    penciler: URIRef
    percentile10: URIRef
    percentile25: URIRef
    percentile75: URIRef
    percentile90: URIRef
    performTime: URIRef
    performer: URIRef
    performerIn: URIRef
    performers: URIRef
    permissionType: URIRef
    permissions: URIRef
    permitAudience: URIRef
    permittedUsage: URIRef
    petsAllowed: URIRef
    phoneticText: URIRef
    photo: URIRef
    photos: URIRef
    physicalRequirement: URIRef
    physiologicalBenefits: URIRef
    pickupLocation: URIRef
    pickupTime: URIRef
    playMode: URIRef
    playerType: URIRef
    playersOnline: URIRef
    polygon: URIRef
    populationType: URIRef
    position: URIRef
    positiveNotes: URIRef
    possibleComplication: URIRef
    possibleTreatment: URIRef
    postOfficeBoxNumber: URIRef
    postOp: URIRef
    postalCode: URIRef
    postalCodeBegin: URIRef
    postalCodeEnd: URIRef
    postalCodePrefix: URIRef
    postalCodeRange: URIRef
    potentialAction: URIRef
    potentialUse: URIRef
    preOp: URIRef
    predecessorOf: URIRef
    pregnancyCategory: URIRef
    pregnancyWarning: URIRef
    prepTime: URIRef
    preparation: URIRef
    prescribingInfo: URIRef
    prescriptionStatus: URIRef
    previousItem: URIRef
    previousStartDate: URIRef
    price: URIRef
    priceComponent: URIRef
    priceComponentType: URIRef
    priceCurrency: URIRef
    priceRange: URIRef
    priceSpecification: URIRef
    priceType: URIRef
    priceValidUntil: URIRef
    primaryImageOfPage: URIRef
    primaryPrevention: URIRef
    printColumn: URIRef
    printEdition: URIRef
    printPage: URIRef
    printSection: URIRef
    procedure: URIRef
    procedureType: URIRef
    processingTime: URIRef
    processorRequirements: URIRef
    producer: URIRef
    produces: URIRef
    productGroupID: URIRef
    productID: URIRef
    productSupported: URIRef
    productionCompany: URIRef
    productionDate: URIRef
    proficiencyLevel: URIRef
    programMembershipUsed: URIRef
    programName: URIRef
    programPrerequisites: URIRef
    programType: URIRef
    programmingLanguage: URIRef
    programmingModel: URIRef
    propertyID: URIRef
    proprietaryName: URIRef
    proteinContent: URIRef
    provider: URIRef
    providerMobility: URIRef
    providesBroadcastService: URIRef
    providesService: URIRef
    publicAccess: URIRef
    publicTransportClosuresInfo: URIRef
    publication: URIRef
    publicationType: URIRef
    publishedBy: URIRef
    publishedOn: URIRef
    publisher: URIRef
    publisherImprint: URIRef
    publishingPrinciples: URIRef
    purchaseDate: URIRef
    qualifications: URIRef
    quarantineGuidelines: URIRef
    query: URIRef
    quest: URIRef
    question: URIRef
    rangeIncludes: URIRef
    ratingCount: URIRef
    ratingExplanation: URIRef
    ratingValue: URIRef
    readBy: URIRef
    readonlyValue: URIRef
    realEstateAgent: URIRef
    recipe: URIRef
    recipeCategory: URIRef
    recipeCuisine: URIRef
    recipeIngredient: URIRef
    recipeInstructions: URIRef
    recipeYield: URIRef
    recipient: URIRef
    recognizedBy: URIRef
    recognizingAuthority: URIRef
    recommendationStrength: URIRef
    recommendedIntake: URIRef
    recordLabel: URIRef
    recordedAs: URIRef
    recordedAt: URIRef
    recordedIn: URIRef
    recordingOf: URIRef
    recourseLoan: URIRef
    referenceQuantity: URIRef
    referencesOrder: URIRef
    refundType: URIRef
    regionDrained: URIRef
    regionsAllowed: URIRef
    relatedAnatomy: URIRef
    relatedCondition: URIRef
    relatedDrug: URIRef
    relatedLink: URIRef
    relatedStructure: URIRef
    relatedTherapy: URIRef
    relatedTo: URIRef
    releaseDate: URIRef
    releaseNotes: URIRef
    releaseOf: URIRef
    releasedEvent: URIRef
    relevantOccupation: URIRef
    relevantSpecialty: URIRef
    remainingAttendeeCapacity: URIRef
    renegotiableLoan: URIRef
    repeatCount: URIRef
    repeatFrequency: URIRef
    repetitions: URIRef
    replacee: URIRef
    replacer: URIRef
    replyToUrl: URIRef
    reportNumber: URIRef
    representativeOfPage: URIRef
    requiredCollateral: URIRef
    requiredGender: URIRef
    requiredMaxAge: URIRef
    requiredMinAge: URIRef
    requiredQuantity: URIRef
    requirements: URIRef
    requiresSubscription: URIRef
    reservationFor: URIRef
    reservationId: URIRef
    reservationStatus: URIRef
    reservedTicket: URIRef
    responsibilities: URIRef
    restPeriods: URIRef
    restockingFee: URIRef
    result: URIRef
    resultComment: URIRef
    resultReview: URIRef
    returnFees: URIRef
    returnLabelSource: URIRef
    returnMethod: URIRef
    returnPolicyCategory: URIRef
    returnPolicyCountry: URIRef
    returnPolicySeasonalOverride: URIRef
    returnShippingFeesAmount: URIRef
    review: URIRef
    reviewAspect: URIRef
    reviewBody: URIRef
    reviewCount: URIRef
    reviewRating: URIRef
    reviewedBy: URIRef
    reviews: URIRef
    riskFactor: URIRef
    risks: URIRef
    roleName: URIRef
    roofLoad: URIRef
    rsvpResponse: URIRef
    runsTo: URIRef
    runtime: URIRef
    runtimePlatform: URIRef
    rxcui: URIRef
    safetyConsideration: URIRef
    salaryCurrency: URIRef
    salaryUponCompletion: URIRef
    sameAs: URIRef
    sampleType: URIRef
    saturatedFatContent: URIRef
    scheduleTimezone: URIRef
    scheduledPaymentDate: URIRef
    scheduledTime: URIRef
    schemaVersion: URIRef
    schoolClosuresInfo: URIRef
    screenCount: URIRef
    screenshot: URIRef
    sdDatePublished: URIRef
    sdLicense: URIRef
    sdPublisher: URIRef
    season: URIRef
    seasonNumber: URIRef
    seasons: URIRef
    seatNumber: URIRef
    seatRow: URIRef
    seatSection: URIRef
    seatingCapacity: URIRef
    seatingType: URIRef
    secondaryPrevention: URIRef
    securityClearanceRequirement: URIRef
    securityScreening: URIRef
    seeks: URIRef
    seller: URIRef
    sender: URIRef
    sensoryRequirement: URIRef
    sensoryUnit: URIRef
    serialNumber: URIRef
    seriousAdverseOutcome: URIRef
    serverStatus: URIRef
    servesCuisine: URIRef
    serviceArea: URIRef
    serviceAudience: URIRef
    serviceLocation: URIRef
    serviceOperator: URIRef
    serviceOutput: URIRef
    servicePhone: URIRef
    servicePostalAddress: URIRef
    serviceSmsNumber: URIRef
    serviceType: URIRef
    serviceUrl: URIRef
    servingSize: URIRef
    sha256: URIRef
    sharedContent: URIRef
    shippingDestination: URIRef
    shippingDetails: URIRef
    shippingLabel: URIRef
    shippingRate: URIRef
    shippingSettingsLink: URIRef
    sibling: URIRef
    siblings: URIRef
    signDetected: URIRef
    signOrSymptom: URIRef
    significance: URIRef
    significantLink: URIRef
    significantLinks: URIRef
    size: URIRef
    sizeGroup: URIRef
    sizeSystem: URIRef
    skills: URIRef
    sku: URIRef
    slogan: URIRef
    smiles: URIRef
    smokingAllowed: URIRef
    sodiumContent: URIRef
    softwareAddOn: URIRef
    softwareHelp: URIRef
    softwareRequirements: URIRef
    softwareVersion: URIRef
    sourceOrganization: URIRef
    sourcedFrom: URIRef
    spatial: URIRef
    spatialCoverage: URIRef
    speakable: URIRef
    specialCommitments: URIRef
    specialOpeningHoursSpecification: URIRef
    specialty: URIRef
    speechToTextMarkup: URIRef
    speed: URIRef
    spokenByCharacter: URIRef
    sponsor: URIRef
    sport: URIRef
    sportsActivityLocation: URIRef
    sportsEvent: URIRef
    sportsTeam: URIRef
    spouse: URIRef
    stage: URIRef
    stageAsNumber: URIRef
    starRating: URIRef
    startDate: URIRef
    startOffset: URIRef
    startTime: URIRef
    status: URIRef
    steeringPosition: URIRef
    step: URIRef
    stepValue: URIRef
    steps: URIRef
    storageRequirements: URIRef
    streetAddress: URIRef
    strengthUnit: URIRef
    strengthValue: URIRef
    structuralClass: URIRef
    study: URIRef
    studyDesign: URIRef
    studyLocation: URIRef
    studySubject: URIRef
    subEvent: URIRef
    subEvents: URIRef
    subOrganization: URIRef
    subReservation: URIRef
    subStageSuffix: URIRef
    subStructure: URIRef
    subTest: URIRef
    subTrip: URIRef
    subjectOf: URIRef
    subtitleLanguage: URIRef
    successorOf: URIRef
    sugarContent: URIRef
    suggestedAge: URIRef
    suggestedAnswer: URIRef
    suggestedGender: URIRef
    suggestedMaxAge: URIRef
    suggestedMeasurement: URIRef
    suggestedMinAge: URIRef
    suitableForDiet: URIRef
    superEvent: URIRef
    supersededBy: URIRef
    supply: URIRef
    supplyTo: URIRef
    supportingData: URIRef
    surface: URIRef
    target: URIRef
    targetCollection: URIRef
    targetDescription: URIRef
    targetName: URIRef
    targetPlatform: URIRef
    targetPopulation: URIRef
    targetProduct: URIRef
    targetUrl: URIRef
    taxID: URIRef
    taxonRank: URIRef
    taxonomicRange: URIRef
    teaches: URIRef
    telephone: URIRef
    temporal: URIRef
    temporalCoverage: URIRef
    termCode: URIRef
    termDuration: URIRef
    termsOfService: URIRef
    termsPerYear: URIRef
    text: URIRef
    textValue: URIRef
    thumbnail: URIRef
    thumbnailUrl: URIRef
    tickerSymbol: URIRef
    ticketNumber: URIRef
    ticketToken: URIRef
    ticketedSeat: URIRef
    timeOfDay: URIRef
    timeRequired: URIRef
    timeToComplete: URIRef
    tissueSample: URIRef
    title: URIRef
    titleEIDR: URIRef
    toLocation: URIRef
    toRecipient: URIRef
    tocContinuation: URIRef
    tocEntry: URIRef
    tongueWeight: URIRef
    tool: URIRef
    torque: URIRef
    totalJobOpenings: URIRef
    totalPaymentDue: URIRef
    totalPrice: URIRef
    totalTime: URIRef
    tourBookingPage: URIRef
    touristType: URIRef
    track: URIRef
    trackingNumber: URIRef
    trackingUrl: URIRef
    tracks: URIRef
    trailer: URIRef
    trailerWeight: URIRef
    trainName: URIRef
    trainNumber: URIRef
    trainingSalary: URIRef
    transFatContent: URIRef
    transcript: URIRef
    transitTime: URIRef
    transitTimeLabel: URIRef
    translationOfWork: URIRef
    translator: URIRef
    transmissionMethod: URIRef
    travelBans: URIRef
    trialDesign: URIRef
    tributary: URIRef
    typeOfBed: URIRef
    typeOfGood: URIRef
    typicalAgeRange: URIRef
    typicalCreditsPerTerm: URIRef
    typicalTest: URIRef
    underName: URIRef
    unitCode: URIRef
    unitText: URIRef
    unnamedSourcesPolicy: URIRef
    unsaturatedFatContent: URIRef
    uploadDate: URIRef
    upvoteCount: URIRef
    url: URIRef
    urlTemplate: URIRef
    usageInfo: URIRef
    usedToDiagnose: URIRef
    userInteractionCount: URIRef
    usesDevice: URIRef
    usesHealthPlanIdStandard: URIRef
    utterances: URIRef
    validFor: URIRef
    validFrom: URIRef
    validIn: URIRef
    validThrough: URIRef
    validUntil: URIRef
    value: URIRef
    valueAddedTaxIncluded: URIRef
    valueMaxLength: URIRef
    valueMinLength: URIRef
    valueName: URIRef
    valuePattern: URIRef
    valueReference: URIRef
    valueRequired: URIRef
    variableMeasured: URIRef
    variantCover: URIRef
    variesBy: URIRef
    vatID: URIRef
    vehicleConfiguration: URIRef
    vehicleEngine: URIRef
    vehicleIdentificationNumber: URIRef
    vehicleInteriorColor: URIRef
    vehicleInteriorType: URIRef
    vehicleModelDate: URIRef
    vehicleSeatingCapacity: URIRef
    vehicleSpecialUsage: URIRef
    vehicleTransmission: URIRef
    vendor: URIRef
    verificationFactCheckingPolicy: URIRef
    version: URIRef
    video: URIRef
    videoFormat: URIRef
    videoFrameSize: URIRef
    videoQuality: URIRef
    volumeNumber: URIRef
    warning: URIRef
    warranty: URIRef
    warrantyPromise: URIRef
    warrantyScope: URIRef
    webCheckinTime: URIRef
    webFeed: URIRef
    weight: URIRef
    weightTotal: URIRef
    wheelbase: URIRef
    width: URIRef
    winner: URIRef
    wordCount: URIRef
    workExample: URIRef
    workFeatured: URIRef
    workHours: URIRef
    workLocation: URIRef
    workPerformed: URIRef
    workPresented: URIRef
    workTranslation: URIRef
    workload: URIRef
    worksFor: URIRef
    worstRating: URIRef
    xpath: URIRef
    yearBuilt: URIRef
    yearlyRevenue: URIRef
    yearsInOperation: URIRef
