import urllib.parse as urlp
from uuid import NAMESPACE_URL as NAMESPACE_URL

SCHEME: str

def is_arcp_uri(uri: str | bytes) -> bool: ...
def parse_arcp(uri) -> ARCPParseResult: ...
def urlparse(uri): ...

class ARCPParseResult(urlp.ParseResult):
    def __init__(self, *args) -> None: ...
    @property
    def prefix(self): ...
    @property
    def name(self): ...
    @property
    def uuid(self): ...
    @property
    def ni(self): ...
    def ni_uri(self, authority: str = ...): ...
    def nih_uri(self): ...
    def ni_well_known(self, base: str = ...): ...
    @property
    def hash(self): ...
