from rdflib import Graph as Graph
from rdflib.namespace import DCTERMS as DCTERMS, OWL as OWL, RDFS as RDFS, SKOS as SKOS
from rdflib.util import guess_format as guess_format

def validate_namespace(namespace) -> None: ...
def validate_object_id(object_id) -> None: ...
def get_target_namespace_elements(g, target_namespace): ...
def make_dn_file(output_file_name, target_namespace, elements_strs, object_id, fail) -> None: ...
