from prov import Error
from typing import Any

class Serializer:
    document: Any
    def __init__(self, document: Any | None = ...) -> None: ...
    def serialize(self, stream, **kwargs) -> None: ...
    def deserialize(self, stream, **kwargs) -> None: ...

class DoNotExist(Error): ...

class Registry:
    serializers: Any
    @staticmethod
    def load_serializers() -> None: ...

def get(format_name): ...
