from prov.constants import *
import json
from prov import Error as Error
from prov.model import Identifier as Identifier, Literal as Literal, Namespace as Namespace, ProvBundle as ProvBundle, ProvDocument as ProvDocument, QualifiedName as QualifiedName, first as first, parse_xsd_datetime as parse_xsd_datetime
from prov.serializers import Serializer as Serializer
from typing import Any

logger: Any

class ProvJSONException(Error): ...

class AnonymousIDGenerator:
    def __init__(self) -> None: ...
    def get_anon_id(self, obj, local_prefix: str = ...): ...

LITERAL_XSDTYPE_MAP: Any

class ProvJSONSerializer(Serializer):
    def serialize(self, stream, **kwargs) -> None: ...
    def deserialize(self, stream, **kwargs): ...

class ProvJSONEncoder(json.JSONEncoder):
    def default(self, o): ...

class ProvJSONDecoder(json.JSONDecoder):
    def decode(self, s, *args, **kwargs): ...

def valid_qualified_name(bundle, value): ...
def encode_json_document(document): ...
def encode_json_container(bundle): ...
def decode_json_document(content, document) -> None: ...
def decode_json_container(jc, bundle) -> None: ...
def encode_json_representation(value): ...
def decode_json_representation(literal, bundle): ...
def literal_json_representation(literal): ...
