from collections.abc import Generator
from rdflib.graph import Graph as Graph
from rdflib.store import Store as Store
from typing import Any

NATIVE_REGEX: int
PYTHON_REGEX: int

class REGEXTerm(str):
    compiledExpr: Any
    def __init__(self, expr) -> None: ...
    def __reduce__(self): ...

def regexCompareQuad(quad, regexQuad): ...

class REGEXMatching(Store):
    storage: Any
    context_aware: Any
    formula_aware: Any
    transaction_aware: Any
    def __init__(self, storage) -> None: ...
    def open(self, configuration, create: bool = ...): ...
    def close(self, commit_pending_transaction: bool = ...) -> None: ...
    def destroy(self, configuration) -> None: ...
    def add(self, triple, context, quoted: bool = ...) -> None: ...
    def remove(self, triple, context: Any | None = ...) -> None: ...
    def triples(self, triple, context: Any | None = ...) -> Generator[Any, None, None]: ...
    def __len__(self, context: Any | None = ...): ...
    def contexts(self, triple: Any | None = ...) -> Generator[Any, None, None]: ...
    def remove_context(self, identifier) -> None: ...
    def bind(self, prefix, namespace) -> None: ...
    def prefix(self, namespace): ...
    def namespace(self, prefix): ...
    def namespaces(self): ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
