import rdflib.parser
from typing import Any

class JsonLDParser(rdflib.parser.Parser):
    def __init__(self) -> None: ...
    def parse(self, source, sink, **kwargs) -> None: ...

def to_rdf(data, dataset, base: Any | None = ..., context_data: Any | None = ..., version: Any | None = ..., generalized_rdf: bool = ..., allow_lists_of_lists: Any | None = ...): ...

class Parser:
    generalized_rdf: Any
    allow_lists_of_lists: Any
    def __init__(self, generalized_rdf: bool = ..., allow_lists_of_lists: Any | None = ...) -> None: ...
    def parse(self, data, context, dataset): ...
