import xml.etree.ElementTree as etree
from collections import Mapping as Mapping, MutableMapping as MutableMapping
from typing import Any

etree_register_namespace = etree.register_namespace

def cast_bytes(s, enc: str = ...): ...
def ascii(stream): ...
def bopen(*args, **kwargs): ...
long_type = int

def sign(n): ...

r_unicodeEscape: Any
narrow_build: bool

def decodeStringEscape(s): ...
def decodeUnicodeEscape(s): ...
