from typing import Any, IO, Optional, Union

class Processor:
    def __init__(self, graph) -> None: ...
    def query(self, strOrQuery, initBindings=..., initNs=..., DEBUG: bool = ...) -> None: ...

class UpdateProcessor:
    def __init__(self, graph) -> None: ...
    def update(self, strOrQuery, initBindings=..., initNs=...) -> None: ...

class ResultException(Exception): ...

class EncodeOnlyUnicode:
    def __init__(self, stream) -> None: ...
    def write(self, arg) -> None: ...
    def __getattr__(self, name): ...

class ResultRow(tuple):
    def __new__(cls, values, labels): ...
    def __getattr__(self, name): ...
    def __getitem__(self, name): ...
    def get(self, name, default: Any | None = ...): ...
    def asdict(self): ...

class Result:
    type: Any
    vars: Any
    askAnswer: Any
    graph: Any
    def __init__(self, type_: str) -> None: ...
    bindings: Any
    @staticmethod
    def parse(source: Any | None = ..., format: Optional[str] = ..., content_type: Optional[str] = ..., **kwargs): ...
    def serialize(self, destination: Optional[Union[str, IO]] = ..., encoding: str = ..., format: str = ..., **args) -> Optional[bytes]: ...
    def __len__(self): ...
    def __bool__(self): ...
    def __iter__(self): ...
    def __getattr__(self, name): ...
    def __eq__(self, other): ...

class ResultParser:
    def __init__(self) -> None: ...
    def parse(self, source, **kwargs) -> None: ...

class ResultSerializer:
    result: Any
    def __init__(self, result: Result) -> None: ...
    def serialize(self, stream: IO, encoding: str = ..., **kwargs): ...
