from rdflib.graph import Graph as Graph
from rdflib.namespace import RDF as RDF
from rdflib.term import BNode as BNode, Identifier as Identifier, Literal as Literal, URIRef as URIRef
from typing import Any

__doc__: str

class Describer:
    graph: Any
    base: Any
    def __init__(self, graph: Any | None = ..., about: Any | None = ..., base: Any | None = ...) -> None: ...
    def about(self, subject, **kws) -> None: ...
    def value(self, p, v, **kws) -> None: ...
    def rel(self, p, o: Any | None = ..., **kws): ...
    def rev(self, p, s: Any | None = ..., **kws): ...
    def rdftype(self, t) -> None: ...

def cast_value(v, **kws): ...
def cast_identifier(ref, **kws): ...
