from typing import Any

logger: Any

def rdflib_to_networkx_multidigraph(graph, edge_attrs=..., **kwds): ...
def rdflib_to_networkx_digraph(graph, calc_weights: bool = ..., edge_attrs=..., **kwds): ...
def rdflib_to_networkx_graph(graph, calc_weights: bool = ..., edge_attrs=..., **kwds): ...
def rdflib_to_graphtool(graph, v_prop_names=..., e_prop_names=..., transform_s=..., transform_p=..., transform_o=...): ...
